"""
Priority-queue alignment algorithm.

See ALGORITHM.md for principles. Reuses xtb / classify_bonds / build_graph
plumbing from rxn_core_frag, but reimplements grow_island and find_islands
on top of a per-fragment priority queue with deferred boundary semantics, branching
on set-non-unique saturation, and chirality-aware scoring.
"""
from __future__ import annotations

import heapq
import itertools
import random
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import networkx as nx

from .frag import (
    run_xtb, build_graph, expand_mapping, classify_bonds,
)

SYM_SUPPORT_MAX_STATES = 4096
SYM_REPAIR_MAX_EVALS = 20000


# -------------------- chemistry-aware post-hoc expansion --------------------

def _edge_wbo(g, a, b):
    """WBO for any atom pair in the complete weighted graph."""
    if a == b:
        return 0.0
    mat = g.graph.get("wbo_matrix")
    if mat is not None:
        return float(mat[a, b])
    if g.has_edge(a, b):
        return float(g[a][b].get("wbo", 0.0))
    return 0.0


def _growth_edge_supported(w_R, w_P, iso_tol):
    """True when a popped traversal edge has a real weighted counterpart.

    The complete-graph iso tolerance is deliberately permissive so changed
    bonds can survive as mechanism boundaries.  But the edge used to grow an
    unchanged island must still be anchored in the target graph; otherwise a
    terminal atom, especially H, can float to any same-element atom because
    `abs(~1.0 - 0.0) <= iso_tol` when `iso_tol == 1`.
    """
    w_R = float(w_R)
    w_P = float(w_P)
    if abs(w_R - w_P) > iso_tol:
        return False
    if w_R > 0.0 and w_P <= 0.0:
        return False
    return abs(_wbo_bucket(w_R) - _wbo_bucket(w_P)) <= 1


def _v_equivalence_class(r, mapping, g_R, g_P, iso_tol=1.0):
    """For an already-mapped atom r with image v = mapping[r], find all
    OTHER P atoms v' that are locally equivalent to v under `mapping`:
      - same element
      - same WBO to mapping[u] for every u in r's R-fragment neighbors
      - same multiset of (element, WBO) for unmapped P-neighbors

    These are the atoms r could have mapped to interchangeably. Returns
    a list of v's including the original v as the first element."""
    v0 = mapping[r]
    n_el = g_R.nodes[r]['element']
    bonded_in_frag = [u for u in g_R.neighbors(r) if u in mapping]
    if not bonded_in_frag:
        return [v0]
    used_p = set(mapping.values())
    sig0 = None
    candidates = [v0]
    # Reference signature for v0
    def sig_of(v):
        unmapped = []
        for w in g_P.neighbors(v):
            if w in used_p or w == v: continue
            unmapped.append((g_P.nodes[w]['element'], round(g_P[v][w]['wbo'], 2)))
        return tuple(sorted(unmapped))
    sig0 = sig_of(v0)
    for v in g_P.nodes():
        if v == v0: continue
        if v in used_p: continue
        if g_P.nodes[v]['element'] != n_el: continue
        # WBO match to mapped fragment neighbors
        ok = True
        for u in bonded_in_frag:
            wR = _edge_wbo(g_R, u, r)
            wP = _edge_wbo(g_P, mapping[u], v)
            if abs(wR - wP) > iso_tol: ok = False; break
        if not ok: continue
        if sig_of(v) != sig0: continue
        candidates.append(v)
    return candidates


def expand_chemistry_relevant_atoms(mapping, broken_R_atoms, g_R, g_P, iso_tol=1.0):
    """Given a canonical bijection and the set of R-atoms that participate
    in broken/formed bonds, enumerate alternative bijections by swapping
    each chemistry-relevant atom's image with members of its equivalence
    class. Returns a list of (mapping, swap_path) tuples, where the
    canonical mapping is first.

    Each alternative is generated by a SWAP: r -> v', and the previous
    occupant of v' -> mapping[r]. We then re-validate WBO consistency on
    every R-edge among the mapped atoms.
    """
    alternatives = [(dict(mapping), [])]
    seen_keys = {tuple(sorted(mapping.items()))}
    for r in broken_R_atoms:
        if r not in mapping: continue
        eqv = _v_equivalence_class(r, mapping, g_R, g_P, iso_tol=iso_tol)
        if len(eqv) <= 1: continue
        v_orig = mapping[r]
        inv = {p: q for q, p in mapping.items()}
        for v_new in eqv[1:]:  # skip the original
            r2 = inv.get(v_new)
            new_m = dict(mapping)
            new_m[r] = v_new
            if r2 is not None:
                new_m[r2] = v_orig
            # Validate all R-edges still match
            valid = True
            for u in new_m:
                for w in g_R.neighbors(u):
                    if w not in new_m or u >= w: continue
                    wR = _edge_wbo(g_R, u, w)
                    pu, pw = new_m[u], new_m[w]
                    if abs(wR - _edge_wbo(g_P, pu, pw)) > iso_tol:
                        valid = False; break
                if not valid: break
            if not valid: continue
            key = tuple(sorted(new_m.items()))
            if key in seen_keys: continue
            seen_keys.add(key)
            alternatives.append((new_m, [(r, v_new)]))
    return alternatives


# -------------------- automorphism-aware orbit dedup --------------------

def _color_refine_orbits(g, iters=20):
    """Iterated color refinement (1-WL / Morgan extended connectivity) on
    an UNLABELED graph. Returns dict node -> int orbit_id such that two
    nodes have the same orbit_id iff they're indistinguishable under
    iterated neighbor-multiset refinement.

    Used to detect symmetric P-atom orbits: bijections that differ only
    by swapping P-atoms in the same orbit produce identical chemistry
    signatures and can be safely collapsed in the cand list.

    For molecules with little symmetry, every atom ends up in its own
    orbit (no collapse). For benzene rings, methyl Hs, B12 carborane,
    etc., symmetric atoms share an orbit and the K-factorial cand
    explosion is avoided.

    Algorithmic correctness: this is the standard 1-WL test used in
    InChI / RDKit canonical SMILES. It's exact for almost all molecular
    graphs and known to fail only on a small class of regular graphs
    (where 2-WL or full automorphism check is needed). For chemistry
    we're safe.
    """
    elements = nx.get_node_attributes(g, 'element')
    # Initial color: just element
    colors = {v: elements.get(v, '') for v in g.nodes()}
    # WBO bucket width: 0.2 so atoms whose WBO differs by ≤0.1 from xtb
    # noise (or geometry distortion at TS) end up in the same orbit.
    # round(x / 0.2) * 0.2 → bucket centers at 0.0, 0.2, 0.4, ...
    def _bucket(w):
        return int(round(w * 5))   # 0.2-wide buckets, integer-keyed
    for _ in range(iters):
        new = {}
        for v in g.nodes():
            nbr = tuple(sorted(
                (colors[w], _bucket(_edge_wbo(g, v, w)))
                for w in g.nodes()
                if w != v
            ))
            new[v] = (colors[v], nbr)
        # Compact to small ints (cheap downstream hashing)
        unique = {c: i for i, c in
                  enumerate(sorted(set(new.values()), key=str))}
        new_int = {v: unique[new[v]] for v in g.nodes()}
        if new_int == colors:
            break
        colors = new_int
    return colors


def _cand_canon_signature(cand, p_orbits):
    """Canonical signature for a cand under unlabeled-g_P orbits.

    Two cands with the same signature differ only by permuting P-atoms
    within their unlabeled orbits — they're spectator-equivalent and
    produce identical chemistry signatures.
    """
    return tuple(sorted((r, p_orbits[p]) for r, p in cand.items()))


def _dedup_cands_by_orbit(cands, p_orbits):
    """Collapse cands that differ only by g_P orbit permutations."""
    if not cands or p_orbits is None or len(cands) == 1:
        return cands
    seen = {}
    for c in cands:
        sig = _cand_canon_signature(c, p_orbits)
        if sig not in seen:
            seen[sig] = c
    return list(seen.values())


def _wbo_bucket(w):
    return int(round(float(w) * 5))


def _orbit_id(orbits, node):
    return orbits[node] if orbits is not None else node


@dataclass(frozen=True)
class _SymBlock:
    """A local symmetry class inside one partial candidate.

    `r_atoms` are already present in the growing R fragment.  `p_atoms` is
    the target pool they occupy up to local symmetry; the candidate stores a
    deterministic concrete witness, but extension/dedup reason over the pool.
    Initial seed pools are not extendable because they represent "where the
    anchor could be", not a sibling class around an already chosen anchor.
    """
    r_atoms: tuple
    p_atoms: tuple
    extendable: bool = True

    def __post_init__(self):
        object.__setattr__(self, 'r_atoms', tuple(sorted(set(self.r_atoms))))
        object.__setattr__(self, 'p_atoms', tuple(sorted(set(self.p_atoms))))

    @property
    def open(self):
        return len(self.r_atoms) < len(self.p_atoms)

    @property
    def complete(self):
        return len(self.r_atoms) >= len(self.p_atoms)


class _SymCand:
    """Compressed partial mapping with symmetry blocks and one witness.

    The public alignment API still consumes concrete dict mappings.  Inside
    growth, this object keeps target pools grouped so a K-fold symmetric target
    produces one candidate instead of K concrete bijections.  `mapping` is the
    deterministic witness used for cheap WBO existence checks.
    """
    __slots__ = ('mapping', 'blocks', 'exact_fixed')

    def __init__(self, mapping=None, blocks=(), exact_fixed=()):
        blocks = tuple(blocks)
        block_r = {r for b in blocks for r in b.r_atoms}
        raw = dict(mapping or {})
        m = {r: p for r, p in raw.items() if r not in block_r}
        used = set(m.values())
        for b in blocks:
            if len(b.r_atoms) > len(b.p_atoms):
                raise ValueError("symmetry block has more R atoms than P atoms")
            for r in b.r_atoms:
                if r not in raw:
                    continue
                p = raw[r]
                if p not in b.p_atoms or p in used:
                    raise ValueError("symmetry block witness conflicts with fixed atoms")
                m[r] = p
                used.add(p)
            available = [p for p in b.p_atoms if p not in used]
            missing = [r for r in b.r_atoms if r not in m]
            if len(available) < len(missing):
                raise ValueError("symmetry block witness conflicts with fixed atoms")
            for r, p in zip(missing, available):
                m[r] = p
                used.add(p)
        self.mapping = m
        self.blocks = blocks
        self.exact_fixed = frozenset(exact_fixed)

    def __contains__(self, r):
        return r in self.mapping

    def __getitem__(self, r):
        return self.mapping[r]

    def get(self, r, default=None):
        return self.mapping.get(r, default)

    def items(self):
        return self.mapping.items()

    def values(self):
        return self.mapping.values()

    def materialize(self):
        return dict(self.mapping)

    def has_open_choice(self):
        return any(b.open for b in self.blocks)

    def with_fixed(self, r, p):
        if r in self.mapping:
            return self if self.mapping[r] == p else None
        if p in self.mapping.values():
            return None
        m = dict(self.mapping)
        m[r] = p
        try:
            return _SymCand(m, self.blocks, self.exact_fixed)
        except ValueError:
            return None

    def with_new_block(self, r, p_atoms, extendable=True):
        p_atoms = tuple(sorted(set(p_atoms)))
        if not p_atoms:
            return None
        if len(p_atoms) == 1:
            return self.with_fixed(r, p_atoms[0])
        if r in self.mapping:
            return None
        b = _SymBlock((r,), p_atoms, extendable=extendable)
        try:
            return _SymCand(self.mapping, self.blocks + (b,),
                            self.exact_fixed)
        except ValueError:
            return None

    def with_extended_block(self, block_idx, r):
        if r in self.mapping:
            return None
        blocks = list(self.blocks)
        b = blocks[block_idx]
        if not b.extendable or b.complete:
            return None
        blocks[block_idx] = _SymBlock(b.r_atoms + (r,), b.p_atoms,
                                      extendable=b.extendable)
        try:
            return _SymCand(self.mapping, blocks, self.exact_fixed)
        except ValueError:
            return None

    def with_witness(self, assignments):
        r_to_block = {}
        for idx, block in enumerate(self.blocks):
            for r in block.r_atoms:
                r_to_block[r] = idx
        touched_blocks = {
            r_to_block[r] for r in assignments
            if r in r_to_block
        }
        m = {
            r: p for r, p in self.mapping.items()
            if r not in r_to_block or r_to_block[r] not in touched_blocks
        }
        m.update(assignments)
        try:
            return _SymCand(m, self.blocks, self.exact_fixed)
        except ValueError:
            return None

    def structural_signature(self, g_R, g_P, r_orbits=None, p_orbits=None):
        block_r = {r for b in self.blocks for r in b.r_atoms}
        fixed = tuple(sorted(
            (('exact', r) if r in self.exact_fixed
             else ('orbit', _orbit_id(r_orbits, r)),
             ('exact', p) if r in self.exact_fixed
             else ('orbit', _orbit_id(p_orbits, p)))
            for r, p in self.mapping.items()
            if r not in block_r
        ))
        blocks = tuple(sorted(
            (
                tuple(sorted(_orbit_id(r_orbits, r) for r in b.r_atoms)),
                len(b.r_atoms),
                tuple(sorted(_orbit_id(p_orbits, p) for p in b.p_atoms)),
                len(b.p_atoms),
                bool(b.extendable),
            )
            for b in self.blocks
        ))
        return fixed, blocks


def _cand_map(cand):
    return cand.materialize() if isinstance(cand, _SymCand) else dict(cand)


def _cand_possible_p_atoms(cand):
    atoms = set(_cand_map(cand).values())
    if isinstance(cand, _SymCand):
        for block in cand.blocks:
            atoms.update(block.p_atoms)
    return atoms


def _cand_has_open_choice(cand):
    return isinstance(cand, _SymCand) and cand.has_open_choice()


def _group_nodes_by_signature(nodes, sig_fn):
    groups = defaultdict(list)
    for node in sorted(nodes):
        groups[sig_fn(node)].append(node)
    return [tuple(vs) for _, vs in sorted(groups.items(), key=lambda kv: str(kv[0]))]


def _p_relation_signature(cand, v, g_P, p_orbits):
    cm = _cand_map(cand)
    rel = []
    for r, p in sorted(cm.items()):
        if p == v:
            continue
        rel.append((r, _wbo_bucket(_edge_wbo(g_P, p, v))))
    block_rel = []
    if isinstance(cand, _SymCand):
        for i, b in enumerate(cand.blocks):
            edge_wbos = []
            for p in b.p_atoms:
                if p == v:
                    continue
                edge_wbos.append(_wbo_bucket(_edge_wbo(g_P, p, v)))
            block_rel.append((i, v in b.p_atoms, tuple(sorted(edge_wbos))))
    return (g_P.nodes[v].get('element'), _orbit_id(p_orbits, v),
            tuple(rel), tuple(block_rel))


def _r_compatible_with_block(cand, block_idx, n, fragment, g_R, r_orbits):
    if not isinstance(cand, _SymCand):
        return False
    b = cand.blocks[block_idx]
    if not b.extendable or b.complete:
        return False
    if r_orbits is not None:
        n_orbit = r_orbits[n]
        if any(r_orbits[r] != n_orbit for r in b.r_atoms):
            return False
    block_r = set(b.r_atoms)
    outside = sorted(r for r in fragment if r not in block_r and r in cand.mapping)

    def rel_sig(r):
        out = []
        for x in outside:
            out.append((x, _wbo_bucket(_edge_wbo(g_R, r, x))))
        return tuple(out)

    n_sig = rel_sig(n)
    return all(rel_sig(r) == n_sig for r in b.r_atoms)


def _boundary_signature(cand, g_R, g_P, fragment=None, deferred_edges=(),
                        r_orbits=None, p_orbits=None, inv=None):
    if not fragment or not deferred_edges:
        return ()
    fragment = set(fragment)
    cm = _cand_map(cand)
    used_possible = _cand_possible_p_atoms(cand)
    inv_used = set(inv or ())

    boundary = set()
    deferred_by_outside = defaultdict(list)
    for raw in deferred_edges or ():
        edge = tuple(raw)
        if len(edge) != 2:
            continue
        a, b = edge
        a_in = a in fragment
        b_in = b in fragment
        if a_in == b_in:
            continue
        inside, outside = (a, b) if a_in else (b, a)
        boundary.add(outside)
        deferred_by_outside[outside].append(inside)

    mapped_rs = sorted(r for r in fragment if r in cm)
    out = []
    for x in sorted(boundary):
        r_vec = tuple(
            (r, _orbit_id(r_orbits, r), _wbo_bucket(_edge_wbo(g_R, x, r)))
            for r in mapped_rs
        )
        target_sigs = []
        x_el = g_R.nodes[x].get('element')
        for v in g_P.nodes():
            if v in inv_used or v in used_possible:
                continue
            if g_P.nodes[v].get('element') != x_el:
                continue
            target_sigs.append(_p_relation_signature(cand, v, g_P, p_orbits))
        counts = Counter(target_sigs)
        p_vec = tuple(sorted(counts.items(), key=lambda item: str(item[0])))
        deferred = tuple(sorted(
            (r, _orbit_id(r_orbits, r), _wbo_bucket(_edge_wbo(g_R, x, r)))
            for r in deferred_by_outside.get(x, [])
        ))
        out.append((_orbit_id(r_orbits, x), x_el, r_vec, deferred, p_vec))
    return tuple(out)


def _dedup_sym_cands(cands, g_R, g_P, r_orbits=None, p_orbits=None,
                     fragment=None, deferred_edges=(), inv=None):
    if not cands:
        return cands
    seen = {}
    for cand in cands:
        if isinstance(cand, _SymCand):
            internal = cand.structural_signature(g_R, g_P, r_orbits, p_orbits)
        elif p_orbits is not None:
            internal = _cand_canon_signature(cand, p_orbits)
        else:
            internal = tuple(sorted(cand.items()))
        boundary = _boundary_signature(
            cand, g_R, g_P, fragment=fragment,
            deferred_edges=deferred_edges, r_orbits=r_orbits,
            p_orbits=p_orbits, inv=inv)
        sig = (internal, boundary)
        if sig not in seen:
            seen[sig] = cand
    return list(seen.values())


def _sym_block_indexes(cand):
    r_to_block = {}
    p_to_block = {}
    if isinstance(cand, _SymCand):
        for idx, block in enumerate(cand.blocks):
            for r in block.r_atoms:
                r_to_block[r] = idx
            for p in block.p_atoms:
                p_to_block[p] = idx
    return r_to_block, p_to_block


def _refine_sym_assignments(cand, assignments):
    """Freeze selected block assignments and shrink the remaining pools.

    This is used when a new atom is valid only under a particular assignment
    inside an existing symmetry block.  Keeping the old block would imply the
    new fixed atom is independent of that block, which is false for cases like
    R37=P38 <=> R104=P119 vs R37=P36 <=> R104=P123.
    """
    if not isinstance(cand, _SymCand):
        m = dict(cand)
        used = {p for r, p in m.items() if r not in assignments}
        for r, p in assignments.items():
            if p in used:
                return None
            m[r] = p
            used.add(p)
        return m

    assignments = dict(assignments)
    if len(set(assignments.values())) != len(assignments):
        return None

    r_to_block, _ = _sym_block_indexes(cand)
    block_r = set(r_to_block)
    m = {r: p for r, p in cand.mapping.items() if r not in block_r}
    used = set(m.values())
    for r, p in sorted(assignments.items()):
        if p in used and m.get(r) != p:
            return None
        m[r] = p
        used.add(p)

    new_blocks = []
    for block in cand.blocks:
        remaining_r = tuple(r for r in block.r_atoms if r not in assignments)
        remaining_p = tuple(p for p in block.p_atoms
                            if p not in assignments.values())
        if not remaining_r:
            continue
        if len(remaining_r) > len(remaining_p):
            return None
        for r in remaining_r:
            p = cand.mapping.get(r)
            if p in remaining_p and p not in used:
                m[r] = p
                used.add(p)
        new_blocks.append(_SymBlock(remaining_r, remaining_p,
                                    extendable=block.extendable))
    exact_fixed = set(cand.exact_fixed)
    try:
        return _SymCand(m, tuple(new_blocks), exact_fixed=exact_fixed)
    except ValueError:
        return None


def _support_witness_for_value(cand, n, v_n, bonded_in_frag, r_wbos,
                               g_P, iso_tol, join_block_idx=None,
                               strict_r_wbos=None,
                               max_states=SYM_SUPPORT_MAX_STATES):
    """Find a concrete witness that supports R[n] -> P[v_n].

    `_SymCand` blocks represent a pool of legal P atoms, but the stored
    mapping is only one witness.  Extension must therefore ask whether some
    assignment inside each unresolved block can satisfy the new edge pattern,
    not whether the current witness happens to satisfy it.
    """
    strict_by_r = dict(strict_r_wbos or ())

    def _pair_ok(r_atom, w_R, p_atom):
        w_P = _edge_wbo(g_P, p_atom, v_n)
        if r_atom in strict_by_r:
            return _growth_edge_supported(strict_by_r[r_atom], w_P, iso_tol)
        return abs(w_R - w_P) <= iso_tol

    if not isinstance(cand, _SymCand):
        used = set(cand.values())
        if v_n in used and cand.get(n) != v_n:
            return None
        support = {}
        for u, w in r_wbos:
            if u not in cand:
                return None
            p_u = cand[u]
            if p_u == v_n:
                return None
            if not _pair_ok(u, w, p_u):
                return None
        return support

    r_to_block, p_to_block = _sym_block_indexes(cand)
    block_r = set(r_to_block)
    fixed_used = {p for r, p in cand.mapping.items() if r not in block_r}
    if v_n in fixed_used and cand.get(n) != v_n:
        return None
    value_block = p_to_block.get(v_n)
    if value_block is not None and value_block != join_block_idx:
        return None
    if join_block_idx is not None:
        block = cand.blocks[join_block_idx]
        if v_n not in block.p_atoms or not block.open:
            return None

    by_block = defaultdict(list)
    support = {}
    w_by_r = {u: w for u, w in r_wbos}
    for u in bonded_in_frag:
        if u not in cand.mapping:
            return None
        bidx = r_to_block.get(u)
        if bidx is None:
            p_u = cand.mapping[u]
            if p_u == v_n:
                return None
            if not _pair_ok(u, w_by_r[u], p_u):
                return None
            continue
        by_block[bidx].append((u, w_by_r[u]))

    for bidx, items in by_block.items():
        block = cand.blocks[bidx]
        reserved = set()
        if bidx == join_block_idx:
            reserved.add(v_n)
        domains = []
        available_pool = [p for p in block.p_atoms if p not in reserved]
        for u, w in items:
            vals = []
            for p in available_pool:
                if _pair_ok(u, w, p):
                    vals.append(p)
            if not vals:
                return None
            domains.append((u, vals))
        if all(set(vals) == set(available_pool) for _, vals in domains):
            continue
        domains.sort(key=lambda item: (len(item[1]), item[0]))
        chosen = {}
        used = set(reserved)
        states = 0

        def backtrack(pos):
            nonlocal states
            states += 1
            if states > max_states:
                return False
            if pos == len(domains):
                return True
            u, vals = domains[pos]
            for p in vals:
                if p in used:
                    continue
                used.add(p)
                chosen[u] = p
                if backtrack(pos + 1):
                    return True
                chosen.pop(u, None)
                used.remove(p)
            return False

        if not backtrack(0):
            return None
        support.update(chosen)
    return support


def _force_sym_value(cand, r, p, fragment, g_R, r_orbits, p_orbits):
    if not isinstance(cand, _SymCand):
        if r in cand:
            return cand if cand[r] == p else None
        if p in cand.values():
            return None
        nc = dict(cand)
        nc[r] = p
        return nc
    r_to_block, p_to_block = _sym_block_indexes(cand)
    if r in cand.mapping:
        current = cand.mapping[r]
        if current == p:
            return cand
        block_idx = r_to_block.get(r)
        if block_idx is None or p not in cand.blocks[block_idx].p_atoms:
            return None
        assignment = {r: p}
        for other in cand.blocks[block_idx].r_atoms:
            if other != r and cand.mapping.get(other) == p:
                assignment[other] = current
                break
        return _refine_sym_assignments(cand, assignment)
    block_idx = p_to_block.get(p)
    if block_idx is not None:
        if not _r_compatible_with_block(cand, block_idx, r, fragment,
                                        g_R, r_orbits):
            return None
        nc = cand.with_extended_block(block_idx, r)
        return _refine_sym_assignments(nc, {r: p}) if nc is not None else None
    block_r = set(r_to_block)
    fixed_used = {v for rr, v in cand.mapping.items() if rr not in block_r}
    if p in fixed_used:
        return None
    return cand.with_fixed(r, p)


# -------------------- core grow --------------------

class _IsoResult(dict):
    __slots__ = ('deferred_edges', 'fragment')

    def __init__(self, mapping=None, deferred_edges=(), fragment=()):
        super().__init__(mapping or {})
        self.deferred_edges = frozenset(tuple(sorted(e)) for e in deferred_edges)
        self.fragment = frozenset(fragment)


def _set_unique(cands):
    """True iff there is at most one fully resolved distinct mapping.

    Earlier this used `frozenset(c.values())` as the equivalence key,
    which collapses every full-bijection candidate to one (since they
    all use the same value-set), silently dropping symmetric variants
    like (R87->IG87, R88->IG88) vs (R87->IG88, R88->IG87). The right
    equivalence for our use is the full bijection itself.  Compressed
    symmetry candidates with an open target pool are not lockable yet;
    they must either absorb enough context or reach saturation first."""
    if not cands:
        return False
    if any(_cand_has_open_choice(c) for c in cands):
        return False
    if len(cands) == 1:
        return True
    sig0 = tuple(sorted(_cand_map(cands[0]).items()))
    return all(tuple(sorted(_cand_map(c).items())) == sig0 for c in cands[1:])


def _push_edges_from(heap, used_edges, g_R, atom, fragment, graph_floor):
    """Push all not-yet-seen outgoing traversal edges of `atom` into the heap."""
    for nb in g_R.neighbors(atom):
        if nb in fragment:
            continue
        edge = frozenset({atom, nb})
        if edge in used_edges:
            continue
        w = g_R[atom][nb]['wbo']
        if w >= graph_floor:
            heapq.heappush(heap, (-w, atom, nb))


def _compute_all_isos_FROM_SCRATCH(fragment, g_R, g_P, mapping, inv, iso_tol,
                      islands_R, max_isos=2000):
    """SLOW: NetworkX subgraph_isomorphisms_iter from scratch.
    Kept for verification; live growth uses `_extend_sym_cands`, which
    applies the same local element/WBO constraints while grouping
    orbit-equivalent targets before child candidates are materialized."""
    sub_R = g_R.subgraph(fragment).copy()
    forced = {r: mapping[r] for r in fragment if r in mapping}
    def nm(nP, nR): return nR['element'] == nP['element']
    def em(eP, eR): return abs(eR['wbo'] - eP['wbo']) <= iso_tol
    matcher = nx.algorithms.isomorphism.GraphMatcher(g_P, sub_R, node_match=nm, edge_match=em)
    isos = []
    for raw in matcher.subgraph_isomorphisms_iter():
        rev = {r: p for p, r in raw.items()}
        ok = True
        for r in fragment:
            if r in forced and rev.get(r) != forced[r]: ok = False; break
            elif r not in forced and rev.get(r) in inv: ok = False; break
        if ok:
            isos.append(rev)
            if len(isos) >= max_isos: break
    return isos


def _extend_cands_incremental(cands, fragment_old, n, g_R, g_P, mapping, inv,
                               iso_tol, islands_R):
    """Legacy concrete incremental extension — NO symmetry compression.

    For each cand:
      - bonded = n's R-neighbors that are in fragment_old (must be in cand)
      - v_set = ⋂(P-neighbors of cand[u]) for u in bonded   minus used_p
      - For each v in v_set with element match, WBO match within iso_tol on
        every bonded edge, and v not in global inv: emit cand ∪ {n: v}.

    Provable equivalence to from-scratch subgraph iso: every iso of
    fragment_new restricts to a complete iso of fragment_old, which must be
    among the existing cands (induction from seed-iso initialization). NO
    pruning — symmetric-atom permutations are kept.  The live path uses
    `_extend_sym_cands` instead, so orbit-equivalent target sets are grouped
    before this concrete fanout would happen.

    Whole-island merge: if n in mapping, n's image is forced to mapping[n],
    and the entire island of n is folded into the cand with consistency
    checks on all cross-bonds within (fragment_old ∪ island).
    """
    n_el = g_R.nodes[n]['element']
    bonded_in_frag = [u for u in g_R.neighbors(n) if u in fragment_old]
    if not bonded_in_frag:
        return None
    r_wbos = [(u, g_R[u][n]['wbo']) for u in bonded_in_frag]

    # Determine target P-atom set and other forced atoms (for whole-island).
    if n in mapping:
        if islands_R is not None and n in islands_R:
            iid = islands_R[n]
            island_atoms = [r for r, k in islands_R.items() if k == iid
                            and r not in fragment_old]
        else:
            island_atoms = [n]
        forced_island = {r: mapping[r] for r in island_atoms}
    else:
        island_atoms = [n]
        forced_island = {}

    new_cands = []
    for cand in cands:
        used_p = set(cand.values())
        # n must map to forced[n] if n is in mapping
        if n in mapping:
            v_n = mapping[n]
            if v_n in used_p and cand.get(n) != v_n:
                continue
            # check forced bond constraints
            ok = True
            for u, w in r_wbos:
                if not g_P.has_edge(cand[u], v_n):
                    ok = False; break
                if abs(w - g_P[cand[u]][v_n]['wbo']) > iso_tol:
                    ok = False; break
            if not ok: continue
            base = dict(cand); base[n] = v_n
            # extend with rest of island atoms (force their images)
            extras_ok = True
            for r in island_atoms:
                if r == n or r in base: continue
                p = mapping[r]
                if p in base.values(): extras_ok = False; break
                base[r] = p
            if not extras_ok: continue
            # verify all R-edges among (island ∪ fragment_old) match in P
            check_set = set(base.keys())
            ok = True
            for r in island_atoms:
                for r2 in g_R.neighbors(r):
                    if r2 not in check_set: continue
                    if r >= r2 and r2 in island_atoms: continue
                    wR = g_R[r][r2]['wbo']
                    p, p2 = base[r], base[r2]
                    if not g_P.has_edge(p, p2): ok = False; break
                    if abs(wR - g_P[p][p2]['wbo']) > iso_tol: ok = False; break
                if not ok: break
            if ok:
                new_cands.append(base)
        else:
            # Free extension: enumerate ALL valid v's for atom n. No pruning,
            # no canonical pick, no 1-hop grouping, no frozenset dedup.
            # Each existing cand fans out to every valid v -> new cand.
            # Mathematically equivalent to from-scratch subgraph iso
            # enumeration (each iso of fragment_new restricts to exactly one
            # iso of fragment_old = one of the existing cands), but O(deg)
            # per cand instead of full VF2 backtracking.
            v_set = set(g_P.neighbors(cand[bonded_in_frag[0]]))
            for u in bonded_in_frag[1:]:
                v_set &= set(g_P.neighbors(cand[u]))
            v_set -= used_p
            for v in v_set:
                if v in inv: continue
                if g_P.nodes[v]['element'] != n_el: continue
                if all(abs(w - g_P[cand[u]][v]['wbo']) <= iso_tol
                       for u, w in r_wbos):
                    nc = dict(cand); nc[n] = v
                    new_cands.append(nc)
    return new_cands


def _extend_sym_cands(cands, fragment_old, n, g_R, g_P, mapping, inv,
                      iso_tol, islands_R, p_orbits=None, r_orbits=None,
                      deferred_edges=(), anchor_u=None, anchor_wbo=None):
    """Symmetry-compressed incremental extension.

    Validity is the complete WBO vector from n to the current fragment.  Valid
    target P atoms are grouped by orbit/context signature before constructing
    children.  A symmetric K-way choice therefore creates one `_SymCand` block
    instead of K concrete dicts; downstream code receives a deterministic
    witness only when the island is committed.
    """
    n_el = g_R.nodes[n]['element']
    bonded_in_frag = sorted(fragment_old)
    if not bonded_in_frag:
        return None
    r_wbos = [(u, _edge_wbo(g_R, u, n)) for u in bonded_in_frag]
    strict_r_wbos = {}
    if anchor_u is not None and anchor_u in fragment_old:
        strict_r_wbos[anchor_u] = (
            _edge_wbo(g_R, anchor_u, n)
            if anchor_wbo is None else anchor_wbo
        )

    if n in mapping:
        if islands_R is not None and n in islands_R:
            iid = islands_R[n]
            island_atoms = [r for r, k in islands_R.items() if k == iid
                            and r not in fragment_old]
        else:
            island_atoms = [n]
    else:
        island_atoms = [n]

    new_cands = []
    for raw_cand in cands:
        cand = raw_cand if isinstance(raw_cand, _SymCand) else _SymCand(raw_cand)
        if any(u not in cand.mapping for u in bonded_in_frag):
            continue

        if n in mapping:
            v_n = mapping[n]
            _, p_to_block = _sym_block_indexes(cand)
            join_idx = p_to_block.get(v_n)
            if join_idx is not None and not _r_compatible_with_block(
                    cand, join_idx, n, fragment_old, g_R, r_orbits):
                continue
            support = _support_witness_for_value(
                cand, n, v_n, bonded_in_frag, r_wbos, g_P, iso_tol,
                join_block_idx=join_idx,
                strict_r_wbos=strict_r_wbos)
            if support is None:
                continue
            nc = _force_sym_value(cand, n, v_n, fragment_old, g_R,
                                  r_orbits, p_orbits)
            if nc is None:
                continue
            support[n] = v_n
            nc = nc.with_witness(support) if isinstance(nc, _SymCand) else nc
            if nc is None:
                continue
            extras_ok = True
            for r in island_atoms:
                if r == n:
                    continue
                p = mapping[r]
                nc = _force_sym_value(nc, r, p, fragment_old, g_R,
                                      r_orbits, p_orbits)
                if nc is None:
                    extras_ok = False; break
            if not extras_ok:
                continue

            base = nc.materialize()
            check_set = set(base.keys())
            ok = True
            for r in island_atoms:
                for r2 in sorted(check_set):
                    if r2 == r:
                        continue
                    if r2 not in check_set:
                        continue
                    if r >= r2 and r2 in island_atoms:
                        continue
                    wR = _edge_wbo(g_R, r, r2)
                    p, p2 = base[r], base[r2]
                    if abs(wR - _edge_wbo(g_P, p, p2)) > iso_tol:
                        ok = False; break
                if not ok:
                    break
            if ok:
                new_cands.append(nc)
            continue

        block_join = []
        by_group = defaultdict(list)
        for v in g_P.nodes():
            if v in inv:
                continue
            if g_P.nodes[v]['element'] != n_el:
                continue
            _, p_to_block = _sym_block_indexes(cand)
            join_idx = p_to_block.get(v)
            if join_idx is not None and not _r_compatible_with_block(
                    cand, join_idx, n, fragment_old, g_R, r_orbits):
                continue
            support = _support_witness_for_value(
                cand, n, v, bonded_in_frag, r_wbos, g_P, iso_tol,
                join_block_idx=join_idx,
                strict_r_wbos=strict_r_wbos)
            if support is None:
                continue
            if join_idx is not None:
                block_join.append((join_idx, v, support))
            else:
                sig = _p_relation_signature(cand, v, g_P, p_orbits)
                by_group[sig].append((v, support))

        for join_idx, v, support in block_join:
            support = dict(support)
            support[n] = v
            if len(support) > 1:
                nc = _refine_sym_assignments(cand, support)
            else:
                nc = cand.with_extended_block(join_idx, n)
                if nc is not None:
                    nc = nc.with_witness(support)
            if nc is not None:
                new_cands.append(nc)

        if not by_group:
            continue
        for _, entries in sorted(by_group.items(), key=lambda kv: str(kv[0])):
            correlated = [(v, support) for v, support in entries if support]
            for v, support in correlated:
                fixed = dict(support)
                fixed[n] = v
                nc = _refine_sym_assignments(cand, fixed)
                if nc is not None:
                    new_cands.append(nc)
            independent = [(v, support) for v, support in entries
                           if not support]
            if not independent:
                continue
            group = tuple(sorted(v for v, _ in independent))
            witness_v, support = sorted(independent, key=lambda item: item[0])[0]
            if len(group) > 1:
                nc = cand.with_new_block(n, group, extendable=True)
            else:
                nc = cand.with_fixed(n, witness_v)
            if nc is not None and isinstance(nc, _SymCand):
                support = dict(support)
                support[n] = witness_v
                nc = nc.with_witness(support)
            if nc is not None:
                new_cands.append(nc)

    sig_fragment = set(fragment_old) | {n}
    for r in island_atoms:
        sig_fragment.add(r)
    return _dedup_sym_cands(
        new_cands, g_R, g_P, r_orbits, p_orbits,
        fragment=sig_fragment, deferred_edges=deferred_edges, inv=inv)


def _merge_whole_island_LEGACY(cands, fragment, n, mapping, islands_R,
                        g_R, g_P, iso_tol):
    """Up-front whole-island merge.

    When propagation reaches an island atom n, pull the ENTIRE island
    (every R-atom whose island_id matches n's) into each cand at once.
    Then check every cross-bond between fragment+island and the rest of
    fragment+island is consistent in P with the existing mapping.

    Returns (new_cands, island_atoms_added). If new_cands is empty, no
    cand survives — caller consumes the edge."""
    if islands_R is None or n not in islands_R:
        # No island bookkeeping; fall back to single-atom semantics.
        island_atoms = [n]
    else:
        target_iid = islands_R[n]
        island_atoms = [r for r, k in islands_R.items() if k == target_iid]
    p_atoms_in_island = [mapping[r] for r in island_atoms]
    new_cands = []
    new_added = [r for r in island_atoms if r not in fragment]
    if not new_added:
        return cands, []  # whole island already absorbed; nothing to do
    for cand in cands:
        # 1) no P-atom in island can be already used by this cand for a
        #    different R-atom
        used_p = set(cand.values())
        if any(p in used_p and cand.get(r) != p
               for r, p in zip(island_atoms, p_atoms_in_island)):
            continue
        # 2) build candidate extension with all island bindings forced
        nc = dict(cand)
        ok = True
        for r, p in zip(island_atoms, p_atoms_in_island):
            if r in nc and nc[r] != p:
                ok = False; break
            nc[r] = p
        if not ok:
            continue
        # 3) check every R-bond between fragment ∪ island (any pair where
        #    at least one endpoint is in island_atoms; the other in
        #    fragment or island_atoms) — the bond must exist in P with
        #    matching WBO. Bonds within fragment alone were checked when
        #    those atoms were added; bonds within island alone are
        #    preserved by construction (the island was locked already).
        check_set = set(island_atoms) | fragment
        for r in island_atoms:
            for r2 in g_R.neighbors(r):
                if r2 not in check_set: continue
                if r2 not in nc:        continue
                if r >= r2 and r2 in island_atoms: continue  # canonicalize
                wR = g_R[r][r2]['wbo']
                p, p2 = nc[r], nc[r2]
                if not g_P.has_edge(p, p2):
                    ok = False; break
                wP = g_P[p][p2]['wbo']
                if abs(wR - wP) > iso_tol:
                    ok = False; break
            if not ok: break
        if ok:
            new_cands.append(nc)
    return new_cands, new_added


def grow_island_pq(g_R, g_P, seed, mapping, inv,
                   graph_floor=0.2,
                   iso_tol=1.0,
                   min_lock_size=1,
                   max_branches=1_000_000,
                   events=None,
                   islands_R=None,
                   p_orbits=None,
                   r_orbits=None,
                   prior_deferred_edges=None):
    """
    Grow a fragment from `seed` using priority-queue propagation.

    Returns a list of isos:
      []            -- failed (no initial cands, or fragment too small)
      [single_iso]  -- locked successfully (set-unique or single cand)
      [iso_a, ...]  -- non-set-unique saturation; caller branches

    Optional `events` list receives diagnostic events (seed_start /
    commit / deferred / merge / seed_end) compatible with the
    existing trace_run.HTML viewer.
    """
    record = events is not None
    if seed in mapping:
        return []
    seed_el = g_R.nodes[seed]['element']
    seed_targets = [v for v in g_P.nodes()
                    if v not in inv and g_P.nodes[v]['element'] == seed_el]
    if p_orbits is not None:
        seed_groups = _group_nodes_by_signature(
            seed_targets, lambda v: (g_P.nodes[v].get('element'),
                                     _orbit_id(p_orbits, v)))
    else:
        seed_groups = [(v,) for v in sorted(seed_targets)]
    cands = []
    for group in seed_groups:
        if len(group) > 1:
            cands.append(_SymCand({seed: group[0]},
                                  (_SymBlock((seed,), group,
                                             extendable=False),)))
        else:
            cands.append(_SymCand({seed: group[0]}))
    if not cands:
        if record:
            events.append({'type': 'seed_start', 'seed': int(seed),
                           'init_cands': 0, 'fragment': [int(seed)],
                           'p_atoms': []})
            events.append({'type': 'seed_end', 'result': 'no_initial_cands',
                           'final_cands': 0, 'fragment': [int(seed)],
                           'iso': None})
        return []
    fragment = {seed}
    distance = {seed: 0}
    used_edges = set()
    deferred_edges = {tuple(sorted(e)) for e in (prior_deferred_edges or ())}
    heap = []
    _push_edges_from(heap, used_edges, g_R, seed, fragment, graph_floor)

    def _cands_sample(cs, k=10):
        return [{int(a): int(b) for a, b in _cand_map(c).items()}
                for c in cs[:k]]

    def _cand_possible_p_atoms(c):
        atoms = set(_cand_map(c).values())
        if isinstance(c, _SymCand):
            for block in c.blocks:
                atoms.update(block.p_atoms)
        return atoms

    def _cand_possible_values(c, r):
        if isinstance(c, _SymCand):
            for block in c.blocks:
                if r in block.r_atoms:
                    return set(block.p_atoms)
        cm = _cand_map(c)
        return {cm[r]} if r in cm else set()

    def _block_assignment_expr(block):
        n = len(block.p_atoms)
        k = len(block.r_atoms)
        if k <= 0 or n <= 1:
            return '1'
        if k == 1:
            return str(n)
        if k == n:
            return f'{n}!'
        return f'P({n},{k})'

    def _cand_assignment_expr(c):
        if not isinstance(c, _SymCand):
            return '1'
        factors = []
        for block in c.blocks:
            expr = _block_assignment_expr(block)
            if expr != '1':
                factors.append(expr)
        return ' * '.join(factors) if factors else '1'

    def _represented_assignment_expr(cs, max_terms=6):
        counts = Counter(_cand_assignment_expr(c) for c in cs)
        if not counts:
            return '0'
        terms = []
        for expr, count in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[:max_terms]:
            if expr == '1':
                terms.append(str(count))
            elif count == 1:
                terms.append(expr)
            else:
                terms.append(f'{count}*({expr})')
        remaining = max(0, len(counts) - max_terms)
        if remaining:
            terms.append(f'... + {remaining} expression groups')
        return ' + '.join(terms)

    def _cands_pattern_sample(cs, k=5):
        out = []
        for c in cs[:k]:
            item = {
                'witness': {int(a): int(b) for a, b in _cand_map(c).items()},
                'blocks': [],
            }
            if isinstance(c, _SymCand):
                for block in c.blocks:
                    item['blocks'].append({
                        'r_atoms': [int(x) for x in block.r_atoms],
                        'p_atoms': [int(x) for x in block.p_atoms],
                        'extendable': bool(block.extendable),
                        'assignments': _block_assignment_expr(block),
                    })
            out.append(item)
        return out

    if record:
        events.append({
            'type': 'seed_start',
            'seed': int(seed),
            'init_cands': len(cands),
            'represented_assignments': _represented_assignment_expr(cands),
            'fragment': [int(seed)],
            'p_atoms': sorted({int(v) for c in cands
                               for v in _cand_possible_p_atoms(c)}),
            'cand_patterns': _cands_pattern_sample(cands, 5),
        })

    def _heap_snapshot(k=None):
        """Pending heap entries sorted by WBO desc, filtered to live
        (not yet popped, not already in fragment). k=None → all."""
        peek = list(heap)
        peek.sort()
        live = [(w, uu, nn) for (w, uu, nn) in peek
                if frozenset({uu, nn}) not in used_edges and nn not in fragment]
        if k is not None:
            live = live[:k]
        return [{'frag_atom': int(uu), 'ext_atom': int(nn),
                 'wbo': round(-w, 3),
                 'ext_status': ('mapped' if nn in mapping
                                else 'free')}
                for w, uu, nn in live]

    def _pool_by_frag_atom():
        """Live propagation pool grouped by fragment atom. Each atom's
        outgoing live edges sorted WBO desc."""
        peek = list(heap)
        peek.sort()
        by_u = defaultdict(list)
        for w, uu, nn in peek:
            if frozenset({uu, nn}) in used_edges: continue
            if nn in fragment: continue
            by_u[int(uu)].append({
                'ext_atom': int(nn),
                'wbo': round(-w, 3),
                'ext_status': ('mapped' if nn in mapping else 'free'),
                'ext_element': g_R.nodes[nn]['element'],
            })
        return [{'frag_atom': int(u),
                 'frag_element': g_R.nodes[u]['element'],
                 'edges': sorted(by_u[u], key=lambda x: -x['wbo'])}
                for u in sorted(by_u.keys())]

    def _why_extend_failed(n_atom, anchor_atom=None, anchor_wbo=None):
        """Per-cand explanation of why extension to n_atom failed."""
        bonded = sorted(fragment)
        n_el = g_R.nodes[n_atom]['element']
        r_wbos = [(u, _edge_wbo(g_R, u, n_atom)) for u in bonded]
        strict_r_wbos = {}
        if anchor_atom is not None and anchor_atom in fragment:
            strict_r_wbos[anchor_atom] = (
                _edge_wbo(g_R, anchor_atom, n_atom)
                if anchor_wbo is None else anchor_wbo
            )
        out = []
        for ci, cand in enumerate(cands[:5]):
            cm = _cand_map(cand)
            used_p = _cand_possible_p_atoms(cand)
            v_set = {
                v for v in g_P.nodes()
                if v not in used_p and v not in inv
                and g_P.nodes[v]['element'] == n_el
            }
            tried = []
            for v in sorted(v_set)[:30]:
                why = []
                _, p_to_block = _sym_block_indexes(cand)
                join_idx = p_to_block.get(v)
                support = _support_witness_for_value(
                    cand, n_atom, v, bonded, r_wbos, g_P, iso_tol,
                    join_block_idx=join_idx,
                    strict_r_wbos=strict_r_wbos)
                if support is None:
                    bad = []
                    for u, w in r_wbos:
                        if u not in cm:
                            continue
                        wp = _edge_wbo(g_P, cm[u], v)
                        if u in strict_r_wbos:
                            if not _growth_edge_supported(
                                    strict_r_wbos[u], wp, iso_tol):
                                bad.append(f'R[{u}]: growth edge |{w:.3f}-{wp:.3f}|={abs(w-wp):.3f} bucket/nonzero fail')
                        elif abs(w - wp) > iso_tol:
                            bad.append(f'R[{u}]: |{w:.3f}-{wp:.3f}|={abs(w-wp):.3f}>{iso_tol}')
                    why.append('; '.join(bad[:5]) if bad else 'no block witness')
                tried.append({'v': int(v), 'rejected': bool(why),
                              'reason': '; '.join(why) if why else 'OK'})
            out.append({
                'cand_idx': ci,
                'cand_at_in_frag_neighbors': {int(u): int(cm[u]) for u in bonded},
                'candidate_v_count': len(v_set),
                'tried_v': tried,
            })
        return out

    def _why_merge_failed(n_atom):
        """Per-cand explanation of why whole-island merge to n_atom failed."""
        if islands_R is None or n_atom not in islands_R:
            island_atoms = [n_atom]
        else:
            target_iid = islands_R[n_atom]
            island_atoms = [r for r, k in islands_R.items() if k == target_iid]
        out = []
        for ci, cand in enumerate(cands[:5]):
            cm = _cand_map(cand)
            why = []
            used_p = set(cm.values())
            for r in island_atoms:
                p = mapping[r]
                if p in used_p and cm.get(r) != p:
                    owner = [k for k, v in cm.items() if v == p][0]
                    why.append(f'P[{p}] (image of R[{r}]) already used by R[{owner}]')
                if r in cm and cm[r] != p:
                    why.append(f'R[{r}] in cand as P[{cm[r]}], conflicts with mapping P[{p}]')
            # cross-bond check
            nc = dict(cm)
            for r, p in [(r, mapping[r]) for r in island_atoms if r not in nc]:
                nc[r] = p
            check_set = set(island_atoms) | fragment
            for r in island_atoms:
                for r2 in sorted(check_set):
                    if r2 == r:
                        continue
                    if r2 not in check_set or r2 not in nc: continue
                    if r >= r2 and r2 in island_atoms: continue
                    wR = _edge_wbo(g_R, r, r2)
                    p, p2 = nc[r], nc[r2]
                    wP = _edge_wbo(g_P, p, p2)
                    if abs(wR - wP) > iso_tol:
                        why.append(f'R[{r}]-R[{r2}]: |{wR:.3f}-{wP:.3f}|={abs(wR-wP):.3f} (P[{p}]-P[{p2}])')
            out.append({'cand_idx': ci, 'reasons': why[:8]})
        return out

    while heap:
        if _set_unique(cands) and len(cands) == 1 and len(fragment) >= min_lock_size:
            if record:
                iso = {int(k): int(v) for k, v in _cand_map(cands[0]).items()}
                events.append({
                    'type': 'seed_end', 'result': 'success',
                    'final_cands': 1,
                    'fragment': sorted(int(x) for x in fragment),
                    'iso': iso,
                    'all_isos': [iso],
                    'lock_reason': 'set_unique_len1_during_BFS',
                    'heap_remaining': len(heap),
                    'cand_patterns': _cands_pattern_sample(cands, 5),
                })
            return [_IsoResult(_cand_map(cands[0]),
                               deferred_edges=deferred_edges,
                               fragment=fragment)]

        neg_w, u, n = heapq.heappop(heap)
        wbo = -neg_w
        edge = frozenset({u, n})
        if edge in used_edges:
            continue
        used_edges.add(edge)
        if n in fragment:
            if record:
                events.append({
                    'type': 'pop_skip',
                    'edge': {'frag_atom': int(u), 'ext_atom': int(n), 'wbo': round(wbo, 3)},
                    'reason': 'ext_atom already in fragment',
                })
            continue

        n_in_mapping = n in mapping
        if record:
            events.append({
                'type': 'pop',
                'edge': {'frag_atom': int(u), 'ext_atom': int(n),
                         'wbo': round(wbo, 3),
                         'ext_element': g_R.nodes[n]['element']},
                'scenario': ('merge_island' if n_in_mapping else 'extend_free'),
                'island_id_at_ext': (int(islands_R[n]) if islands_R and n in islands_R else None),
                'island_image': (int(mapping[n]) if n_in_mapping else None),
                'pre_state': {
                    'fragment_size': len(fragment),
                    'fragment': sorted(int(x) for x in fragment),
                    'cands_count': len(cands),
                    'represented_assignments': _represented_assignment_expr(cands),
                    'cands_sample': _cands_sample(cands, 5),
                    'cands_pattern_sample': _cands_pattern_sample(cands, 5),
                    'p_atoms_in_cands': sorted({int(v) for c in cands
                                                for v in _cand_possible_p_atoms(c)}),
                },
                'heap_top_after_pop': _heap_snapshot(8),
                'pool_by_frag_atom': _pool_by_frag_atom(),
            })

        # Tentatively add n to the shared fragment. If any weighted extension
        # survives, commit it; otherwise record this edge as deferred boundary.
        old_count = len(cands)
        old_fragment = set(fragment)
        candidate_fragment = fragment | {n}
        # Symmetry-compressed incremental extension.  It applies the same
        # element/WBO checks as the concrete incremental matcher, but groups
        # target atoms by local orbit/context before constructing children.
        new_cands = _extend_sym_cands(
            cands, fragment, n, g_R, g_P, mapping, inv,
            iso_tol, islands_R, p_orbits=p_orbits, r_orbits=r_orbits,
            deferred_edges=deferred_edges, anchor_u=u, anchor_wbo=wbo)
        if new_cands:
            cands = new_cands
            ref_dist = distance.get(u, 0) + 1
            if n_in_mapping and islands_R is not None and n in islands_R:
                target_iid = islands_R[n]
                whole_island = [r for r, k in islands_R.items() if k == target_iid]
                candidate_fragment = candidate_fragment | set(whole_island)
                added_extra = [r for r in whole_island if r not in distance]
                for r in added_extra:
                    distance[r] = ref_dist
            fragment = candidate_fragment
            for r in fragment - old_fragment:
                if r not in distance:
                    distance[r] = ref_dist
                _push_edges_from(heap, used_edges, g_R, r, fragment, graph_floor)
            if record:
                added_atoms = sorted(int(r) for r in fragment - old_fragment)
                events.append({
                    'type': 'commit',
                    'scenario': ('merge_island' if n_in_mapping else 'extend_free'),
                    'edge': {'frag_atom': int(u), 'ext_atom': int(n), 'wbo': round(wbo, 3)},
                    'added': int(n), 'element': g_R.nodes[n]['element'],
                    'atoms_added': added_atoms,
                    'island_size_absorbed': len(added_atoms) if n_in_mapping else None,
                    'island_image': int(mapping[n]) if n_in_mapping else None,
                    'cand_n_value_set': sorted({int(v) for c in cands
                                                for v in _cand_possible_values(c, n)}),
                    'cands_before': old_count,
                    'cands_after': len(cands),
                    'represented_assignments_after': _represented_assignment_expr(cands),
                    'cands_sample_after': _cands_sample(cands, 5),
                    'cands_pattern_after': _cands_pattern_sample(cands, 5),
                    'fragment': sorted(int(x) for x in fragment),
                    'p_atoms': sorted({int(v) for c in cands
                                       for v in _cand_possible_p_atoms(c)}),
                    'distance_from_seed': distance[n],
                    'bonds_to_fragment': [(int(u), round(wbo, 3))],
                    'heap_remaining': len(heap),
                    'heap_top': _heap_snapshot(8),
                    'pool_by_frag_atom': _pool_by_frag_atom(),
                })
        else:
            deferred_edges.add(tuple(sorted((u, n))))
            if record:
                events.append({
                    'type': 'consumed',
                    'deferred': True,
                    'scenario': ('merge_island' if n_in_mapping else 'extend_free'),
                    'edge': {'frag_atom': int(u), 'ext_atom': int(n), 'wbo': round(wbo, 3),
                             'ext_element': g_R.nodes[n]['element']},
                    'reason': ('merge_failed' if n_in_mapping else 'cut_all_cands'),
                    'island_image': int(mapping[n]) if n_in_mapping else None,
                    'island_id': int(islands_R[n]) if islands_R and n in islands_R else None,
                    'why_per_cand': (_why_merge_failed(n) if n_in_mapping
                                     else _why_extend_failed(n, u, wbo)),
                    'cands_count': len(cands),
                    'represented_assignments': _represented_assignment_expr(cands),
                    'cands_sample': _cands_sample(cands, 5),
                    'cands_pattern_sample': _cands_pattern_sample(cands, 5),
                    'fragment': sorted(int(x) for x in fragment),
                    'heap_remaining': len(heap),
                    'heap_top': _heap_snapshot(8),
                    'pool_by_frag_atom': _pool_by_frag_atom(),
                })

    # heap empty
    if not cands or len(fragment) < min_lock_size:
        if record:
            events.append({
                'type': 'seed_end',
                'result': ('no_cands' if not cands else 'too_small'),
                'final_cands': len(cands),
                'fragment': sorted(int(x) for x in fragment),
                'iso': None,
            })
        return []
    if _set_unique(cands):
        if record:
            iso_map = _cand_map(cands[0])
            iso = {int(k): int(v) for k, v in iso_map.items()}
            events.append({
                'type': 'seed_end', 'result': 'success',
                'final_cands': len(cands),
                'fragment': sorted(int(x) for x in fragment),
                'iso': iso,
                'all_isos': [iso],
                'cand_patterns': _cands_pattern_sample(cands, 5),
            })
        return [_IsoResult(_cand_map(cands[0]),
                           deferred_edges=deferred_edges,
                           fragment=fragment)]
    # Dedup by compressed structural signature.  Open symmetry blocks may
    # still contain many concrete witnesses; only one deterministic witness
    # is returned for each orbit/context-distinct saturation.
    by_set = {}
    for c in cands:
        if isinstance(c, _SymCand):
            key = (
                c.structural_signature(g_R, g_P, r_orbits, p_orbits),
                _boundary_signature(
                    c, g_R, g_P, fragment=fragment,
                    deferred_edges=deferred_edges, r_orbits=r_orbits,
                    p_orbits=p_orbits, inv=inv),
            )
        elif p_orbits is not None:
            key = (
                _cand_canon_signature(c, p_orbits),
                _boundary_signature(
                    c, g_R, g_P, fragment=fragment,
                    deferred_edges=deferred_edges, r_orbits=r_orbits,
                    p_orbits=p_orbits, inv=inv),
            )
        else:
            key = (
                tuple(sorted(c.items())),
                _boundary_signature(
                    c, g_R, g_P, fragment=fragment,
                    deferred_edges=deferred_edges, r_orbits=r_orbits,
                    p_orbits=p_orbits, inv=inv),
            )
        if key not in by_set:
            by_set[key] = _IsoResult(
                _cand_map(c), deferred_edges=deferred_edges,
                fragment=fragment)
    branches = list(by_set.values())[:max_branches]
    if record:
        events.append({
            'type': 'seed_end', 'result': 'branched',
            'final_cands': len(cands), 'n_branches': len(branches),
            'fragment': sorted(int(x) for x in fragment),
            'iso': {int(k): int(v) for k, v in branches[0].items()},
            'all_isos': [{int(k): int(v) for k, v in c.items()}
                         for c in branches],
            'cand_patterns': _cands_pattern_sample(cands, 10),
        })
    return branches


# -------------------- BFS frontier search --------------------

def grow_island_bfs(g_R, g_P, seed, mapping, inv,
                    graph_floor=0.2, iso_tol=1.0,
                    min_lock_size=1, events=None,
                    islands_R=None, max_branches=1_000_000):
    """EXPERIMENTAL: BFS frontier search over partial mappings.

    Status: kept for reference, not wired into find_islands_pq because
    it explodes on real molecules. The naive BFS spawns one child per
    valid (R_neighbor, P_target) extension; even with mapping-signature
    dedup, the state space grows multiplicatively because different
    growth orders can land on different INTERMEDIATE mappings that don't
    converge until very late.

    The current grow_island_pq avoids this by maintaining ONE shared
    fragment (deterministic growth order via WBO heap) and tracking
    multiple bijections of that single fragment as the cands list. The
    result is the same set of saturation bijections, but with bounded
    intermediate state count.

    A working BFS replacement would need either:
      - a canonical fragment-growth order (e.g., always extend the
        lowest-index frontier atom) so all states share a fragment, OR
      - a smarter dedup that canonicalizes mappings up to spectator
        permutations earlier in the search.

    Left here as a starting point for future work.
    """
    record = events is not None
    if seed in mapping:
        return []
    seed_el = g_R.nodes[seed]['element']

    init_isos = []
    for v in g_P.nodes():
        if v in inv: continue
        if g_P.nodes[v]['element'] != seed_el: continue
        init_isos.append({seed: v})

    if not init_isos:
        if record:
            events.append({'type': 'seed_start', 'seed': int(seed),
                           'init_cands': 0, 'fragment': [int(seed)],
                           'p_atoms': []})
            events.append({'type': 'seed_end', 'result': 'no_initial_cands',
                           'final_cands': 0, 'fragment': [int(seed)],
                           'iso': None})
        return []

    if record:
        events.append({'type': 'seed_start', 'seed': int(seed),
                       'init_cands': len(init_isos),
                       'fragment': [int(seed)],
                       'p_atoms': sorted(int(c[seed]) for c in init_isos)})

    # Frontier: set of frozensets of (R, P) pairs. Use frozenset for O(1)
    # dedup of partial-mapping states.
    frontier = {frozenset(m.items()) for m in init_isos}
    saturated = set()
    bfs_level = 0

    while frontier:
        bfs_level += 1
        next_frontier = set()
        for state in frontier:
            m = dict(state)
            mapped_R = set(m.keys())
            mapped_P = set(m.values())
            extensions_made = False
            # Iterate every fragment atom; for each, enumerate every
            # valid (n, v) extension. The dedup at next_frontier collapses
            # duplicates from different atom-pick orders.
            for r in mapped_R:
                for n in g_R.neighbors(r):
                    if n in mapped_R: continue
                    if g_R[r][n]['wbo'] < graph_floor: continue
                    if n in mapping: continue  # globally locked
                    n_el = g_R.nodes[n]['element']
                    bonded_to_n = [u for u in g_R.neighbors(n)
                                   if u in mapped_R
                                   and g_R[u][n]['wbo'] >= graph_floor]
                    if not bonded_to_n: continue
                    p_cands = set(g_P.neighbors(m[bonded_to_n[0]]))
                    for u in bonded_to_n[1:]:
                        p_cands &= set(g_P.neighbors(m[u]))
                    p_cands -= mapped_P
                    p_cands -= set(inv.keys())
                    for v in p_cands:
                        if g_P.nodes[v]['element'] != n_el: continue
                        ok = True
                        for u in bonded_to_n:
                            wR = g_R[u][n]['wbo']
                            wP = g_P[m[u]][v]['wbo']
                            if abs(wR - wP) > iso_tol:
                                ok = False; break
                        if not ok: continue
                        new_m = dict(m); new_m[n] = v
                        next_frontier.add(frozenset(new_m.items()))
                        extensions_made = True
            if not extensions_made:
                saturated.add(state)
        frontier = next_frontier
        if len(saturated) > max_branches:
            break

    # Saturation can produce many tied bijections (different P targets for
    # symmetric atoms). The frozenset already deduped by mapping signature,
    # so just convert back to dicts.
    result = []
    for fro in saturated:
        m = {r: v for r, v in fro}
        if len(m) >= min_lock_size:
            result.append(m)

    if record:
        if not result:
            events.append({'type': 'seed_end',
                           'result': 'no_cands' if not saturated else 'too_small',
                           'final_cands': 0,
                           'fragment': [int(seed)],
                           'iso': None})
        else:
            ref_frag = sorted(int(x) for x in result[0].keys())
            iso0 = {int(k): int(v) for k, v in result[0].items()}
            evt = {
                'type': 'seed_end',
                'result': 'success' if len(result) == 1 else 'branched',
                'final_cands': len(result),
                'n_branches': len(result),
                'fragment': ref_frag,
                'iso': iso0,
                'all_isos': [{int(k): int(v) for k, v in m.items()}
                             for m in result],
                'bfs_levels': bfs_level,
            }
            events.append(evt)
    return result


# -------------------- find_islands with branching --------------------

class _Branch:
    __slots__ = ('mapping', 'inv', 'islands_R', 'islands_P', 'next_iid',
                 'deferred_edges')
    def __init__(self):
        self.mapping = {}
        self.inv = {}
        self.islands_R = {}
        self.islands_P = {}
        self.next_iid = 1
        self.deferred_edges = set()
    def fork(self):
        b = _Branch()
        b.mapping = dict(self.mapping)
        b.inv = dict(self.inv)
        b.islands_R = dict(self.islands_R)
        b.islands_P = dict(self.islands_P)
        b.next_iid = self.next_iid
        b.deferred_edges = set(self.deferred_edges)
        return b
    def commit(self, iso, g_R, events=None):
        touched = set()
        for r in iso:
            if r in self.islands_R:
                touched.add(self.islands_R[r])
        if touched:
            iid = min(touched)
        else:
            iid = self.next_iid
            self.next_iid += 1
        committed_new = []
        relabeled = []
        for r, p in iso.items():
            if r not in self.mapping:
                self.mapping[r] = p
                self.inv[p] = r
                committed_new.append((int(r), int(p)))
            elif self.islands_R.get(r) != iid:
                relabeled.append((int(r), int(self.islands_R[r])))
            self.islands_R[r] = iid
            self.islands_P[p] = iid
        self.deferred_edges.update(getattr(iso, 'deferred_edges', ()))
        for r, k in list(self.islands_R.items()):
            if k in touched and k != iid:
                relabeled.append((int(r), int(k)))
                self.islands_R[r] = iid
                self.islands_P[self.mapping[r]] = iid
        if events is not None:
            events.append({
                'type': 'island_locked',
                'island_idx': int(iid),
                'pairs': committed_new,
                'merged_with': sorted(int(t) for t in touched - {iid}),
                'relabeled': relabeled,
                'mapped_total': len(self.mapping),
            })


def _orbit_pair(a, b, orbits):
    oa, ob = _orbit_id(orbits, a), _orbit_id(orbits, b)
    return (oa, ob) if oa <= ob else (ob, oa)


def _chemistry_orbit_signature(mapping, g_R, g_P, r_orbits=None, p_orbits=None,
                               dwbo_threshold=0.5):
    """Broken/formed bond signature in joint R-orbit/P-orbit space."""
    br_pairs = []
    fm_pairs = []
    mapped = sorted(mapping)
    for i, u in enumerate(mapped):
        for v in mapped[i + 1:]:
            pu, pv = mapping[u], mapping[v]
            wR = _edge_wbo(g_R, u, v)
            wP = _edge_wbo(g_P, pu, pv)
            if wR - wP >= dwbo_threshold:
                br_pairs.append((
                    _orbit_pair(u, v, r_orbits),
                    _orbit_pair(pu, pv, p_orbits),
                ))
            elif wP - wR >= dwbo_threshold:
                fm_pairs.append((
                    _orbit_pair(u, v, r_orbits),
                    _orbit_pair(pu, pv, p_orbits),
                ))
    return tuple(sorted(br_pairs)), tuple(sorted(fm_pairs))


def _alignment_state_signature(mapping, deferred_edges, g_R, g_P,
                               r_orbits=None, p_orbits=None, core_R=()):
    core_R = tuple(sorted(core_R or ()))
    core_set = set(core_R)
    fixed = []
    for r, p in sorted(mapping.items()):
        if r in core_set:
            fixed.append((('exact', r), ('exact', p)))
        else:
            fixed.append((
                ('orbit', _orbit_id(r_orbits, r)),
                ('orbit', _orbit_id(p_orbits, p)),
            ))
    internal_pairs = []
    mapped = sorted(mapping)
    for i, r1 in enumerate(mapped):
        for r2 in mapped[i + 1:]:
            p1, p2 = mapping[r1], mapping[r2]
            internal_pairs.append((
                _orbit_pair(r1, r2, r_orbits),
                _orbit_pair(p1, p2, p_orbits),
                _wbo_bucket(_edge_wbo(g_R, r1, r2)),
                _wbo_bucket(_edge_wbo(g_P, p1, p2)),
            ))
    boundary = _boundary_signature(
        mapping, g_R, g_P, fragment=set(mapping),
        deferred_edges=deferred_edges, r_orbits=r_orbits,
        p_orbits=p_orbits, inv={p: r for r, p in mapping.items()})
    return tuple(fixed), tuple(sorted(internal_pairs)), boundary


def _mapping_change_score(mapping, wbo_R, wbo_P, dwbo_threshold=0.5):
    broken, formed, _, _ = classify_bonds(
        mapping, wbo_R, wbo_P, dwbo_threshold=dwbo_threshold)
    delta = 0.0
    for a, b, wR, wP in broken:
        delta += abs(float(wR or 0.0) - float(wP or 0.0))
    for a, b, wR, wP in formed:
        delta += abs(float(wP or 0.0) - float(wR or 0.0))
    return (len(broken) + len(formed), round(delta, 12), -len(mapping))


def symmetry_repair_mapping(mapping, wbo_R, wbo_P, g_R, g_P, p_orbits,
                            dwbo_threshold=0.5, bond_floor=0.2,
                            min_changes=5, full_permutation_size=6,
                            max_evals=SYM_REPAIR_MAX_EVALS,
                            return_stats=False):
    """Choose the best concrete realization inside product symmetry orbits.

    The PQ matcher intentionally compresses high-symmetry choices and keeps a
    single witness.  A witness is not chemistry: if changed-bond endpoints sit
    inside an unresolved P orbit, another realization of the same compressed
    match may remove fake broken/formed bonds.  This local search swaps
    only atoms that already occupy the same product orbit and element.
    """
    if not mapping or p_orbits is None:
        return (mapping, {'enabled': False}) if return_stats else mapping
    mapping0 = dict(mapping)
    base_broken, base_formed, _, _ = classify_bonds(
        mapping0, wbo_R, wbo_P, dwbo_threshold=dwbo_threshold)
    base_changes = len(base_broken) + len(base_formed)
    stats = {
        'enabled': True,
        'base_changes': int(base_changes),
        'repaired': False,
        'groups': [],
        'evaluated': 0,
        'capped': False,
    }
    if base_changes < min_changes:
        return (mapping0, stats) if return_stats else mapping0

    inv = {v: r for r, v in mapping0.items()}
    affected = set()
    for a, b, _, _ in base_broken:
        affected.add(a); affected.add(b)
    for a, b, _, _ in base_formed:
        if a in inv:
            affected.add(inv[a])
        if b in inv:
            affected.add(inv[b])
    if not affected:
        return (mapping0, stats) if return_stats else mapping0

    local = set(affected)
    for r in list(affected):
        if r not in g_R:
            continue
        for nb in g_R.neighbors(r):
            if g_R[r][nb].get('wbo', 0.0) >= bond_floor:
                local.add(nb)
    for p in {x for edge in base_formed for x in edge[:2]}:
        if p not in g_P:
            continue
        for q in g_P.neighbors(p):
            if q in inv and g_P[p][q].get('wbo', 0.0) >= bond_floor:
                local.add(inv[q])

    touched_orbits = set()
    for r in affected:
        if r in mapping0:
            p = mapping0[r]
            touched_orbits.add((g_R.nodes[r].get('element'), p_orbits[p]))
    groups = defaultdict(list)
    for r, p in mapping0.items():
        key = (g_R.nodes[r].get('element'), p_orbits[p])
        if key in touched_orbits:
            groups[key].append(r)
    groups = {
        key: sorted(rs) for key, rs in groups.items()
        if len(rs) > 1
    }
    if not groups:
        return (mapping0, stats) if return_stats else mapping0

    local_pairs = []
    nR = wbo_R.shape[0]
    for i in range(nR):
        for j in range(i + 1, nR):
            if i not in mapping0 or j not in mapping0:
                continue
            if i not in local and j not in local:
                continue
            local_pairs.append((i, j, float(wbo_R[i, j])))

    def local_score(m):
        changed = 0
        delta = 0.0
        for i, j, wR in local_pairs:
            wP = float(wbo_P[m[i], m[j]])
            if wR - wP >= dwbo_threshold:
                changed += 1
                delta += wR - wP
            elif wP - wR >= dwbo_threshold:
                changed += 1
                delta += wP - wR
            elif wR >= bond_floor or wP >= bond_floor:
                delta += abs(wR - wP) * 0.01
        return (changed, round(delta, 12), -len(m))

    current = dict(mapping0)
    current_score = local_score(current)
    for key, rs in sorted(groups.items(), key=lambda item: (-len(item[1]), item[0])):
        stats['groups'].append({
            'element': key[0],
            'orbit': int(key[1]),
            'size': len(rs),
            'atoms': [int(r) for r in rs],
        })
    max_passes = max(4, 2 * sum(len(rs) for rs in groups.values()))
    ordered_groups = [rs for _, rs in sorted(
        groups.items(), key=lambda item: (-len(item[1]), item[0]))]
    for _ in range(max_passes):
        improved = False
        for rs in ordered_groups:
            if stats['evaluated'] >= max_evals:
                stats['capped'] = True
                break
            best_score = current_score
            best_map = None
            if len(rs) <= full_permutation_size:
                targets = [current[r] for r in rs]
                for perm in itertools.permutations(targets):
                    if stats['evaluated'] >= max_evals:
                        stats['capped'] = True
                        break
                    candidate = dict(current)
                    for r, p in zip(rs, perm):
                        candidate[r] = p
                    score = local_score(candidate)
                    stats['evaluated'] += 1
                    if score < best_score:
                        best_score = score
                        best_map = candidate
            else:
                for a, b in itertools.combinations(rs, 2):
                    if stats['evaluated'] >= max_evals:
                        stats['capped'] = True
                        break
                    candidate = dict(current)
                    candidate[a], candidate[b] = candidate[b], candidate[a]
                    score = local_score(candidate)
                    stats['evaluated'] += 1
                    if score < best_score:
                        best_score = score
                        best_map = candidate
            if best_map is not None:
                current = best_map
                current_score = best_score
                improved = True
        if stats['capped']:
            break
        if not improved:
            break

    best = current
    best_score = _mapping_change_score(best, wbo_R, wbo_P,
                                       dwbo_threshold=dwbo_threshold)
    base_score = _mapping_change_score(mapping0, wbo_R, wbo_P,
                                       dwbo_threshold=dwbo_threshold)
    stats['best_changes'] = int(best_score[0])
    if best_score < base_score:
        stats['repaired'] = True
        return (best, stats) if return_stats else best
    return (mapping0, stats) if return_stats else mapping0


def find_islands_pq(g_R, g_P, seed_order,
                    graph_floor=0.2, iso_tol=1.0,
                    max_branches=1_000_000, events=None,
                    orbit_dedup=True, core_R=None,
                    stop_when_core_mapped=False):
    """Run growth over a single seed ordering, branching on
    non-set-unique locks. Returns list of _Branch.

    Optional `events` only records the FIRST (best-mapped) branch's
    trajectory — multi-branch traces would be confusing on a slider.

    orbit_dedup: when True (default), pre-computes both g_R's and g_P's
    automorphism color classes once via iterated 1-WL color refinement.
    Used as a CHEAP FILTER for orbit-equivalence; chemistry signature
    in orbit space is the VERIFIER. Prevents K-factorial explosion on
    high-symmetry molecules.

    core_R: optional R atoms that define the scoring-relevant alignment.
    When supplied, branch dedup switches to exact core mapping as soon as
    every core atom is mapped.  With stop_when_core_mapped=True the search
    returns once all live branches have mapped the core, leaving spectators
    to downstream greedy fill.
    """
    p_orbits = _color_refine_orbits(g_P) if orbit_dedup else None
    r_orbits = _color_refine_orbits(g_R) if orbit_dedup else None
    core_R = tuple(sorted(set(core_R or ())))
    core_R_set = set(core_R)
    seed_order = list(seed_order)
    if core_R:
        seed_order = ([s for s in seed_order if s in core_R_set] +
                      [s for s in seed_order if s not in core_R_set])
    branches = [_Branch()]
    progressed = True
    pass_no = 0

    def _core_complete(mapping):
        return core_R and all(r in mapping for r in core_R)

    def _branch_signature(mapping, deferred_edges=()):
        core_key = tuple((r, mapping[r]) for r in core_R if r in mapping)
        if core_R and len(core_key) == len(core_R):
            return ('core_complete', core_key)
        deferred_boundary = _boundary_signature(
            mapping, g_R, g_P, fragment=set(mapping),
            deferred_edges=deferred_edges, r_orbits=r_orbits,
            p_orbits=p_orbits, inv={p: r for r, p in mapping.items()})
        return (
            'mechanism_state',
            core_key,
            _chemistry_orbit_signature(
                mapping, g_R, g_P, r_orbits, p_orbits),
            deferred_boundary,
        )

    while progressed:
        progressed = False
        pass_no += 1
        if events is not None:
            events.append({'type': 'pass_start', 'pass': pass_no,
                           'mapped': len(branches[0].mapping)})
        for seed in seed_order:
            new_branches = []
            pending_seen = set()

            def _append_pending(branch):
                sig = _branch_signature(branch.mapping, branch.deferred_edges)
                if sig in pending_seen:
                    return False
                pending_seen.add(sig)
                new_branches.append(branch)
                return True

            for bi, b in enumerate(branches):
                if len(new_branches) >= max_branches:
                    break
                if stop_when_core_mapped and _core_complete(b.mapping):
                    _append_pending(b)
                    continue
                if seed in b.mapping:
                    _append_pending(b)
                    continue
                # Only record events for branch 0 to keep trace linear
                ev_arg = events if (events is not None and bi == 0) else None
                isos = grow_island_pq(g_R, g_P, seed, b.mapping, b.inv,
                                      graph_floor=graph_floor, iso_tol=iso_tol,
                                      max_branches=max_branches,
                                      events=ev_arg,
                                      islands_R=b.islands_R,
                                      p_orbits=p_orbits,
                                      r_orbits=r_orbits,
                                      prior_deferred_edges=b.deferred_edges)
                if not isos:
                    _append_pending(b)
                    continue
                # Dedup island results by weighted alignment state before
                # forking branches.  This is still pre-mechanism dedupe: the
                # one-hop/deferred boundary is part of the key so future
                # distinguishability is not erased.
                seen_state = {}
                for iso in isos:
                    full_m = dict(b.mapping); full_m.update(iso)
                    full_deferred = set(b.deferred_edges)
                    full_deferred.update(getattr(iso, 'deferred_edges', ()))
                    state_key = _branch_signature(full_m, full_deferred)
                    if state_key not in seen_state:
                        seen_state[state_key] = iso
                deduped_isos = list(seen_state.values())
                for ii, iso in enumerate(deduped_isos):
                    if len(new_branches) >= max_branches:
                        break
                    b2 = b.fork()
                    b2.commit(iso, g_R,
                              events=events if (bi == 0 and ii == 0) else None)
                    if _append_pending(b2):
                        progressed = True
            new_branches.sort(key=lambda b: -len(b.mapping))
            # Cross-branch dedup uses the same mechanism-state key.  It
            # collapses orbit-equivalent spectator permutations but keeps
            # states separated when their deferred one-hop boundary differs.
            seen = set()
            uniq = []
            for b in new_branches:
                state_sig = _branch_signature(b.mapping, b.deferred_edges)
                if state_sig in seen:
                    continue
                seen.add(state_sig)
                uniq.append(b)
                if len(uniq) >= max_branches:
                    break
            branches = uniq
            # Soft warning: pathological symmetry can blow this up. Default
            # cap is 1e6 so we should never hit it on real molecules; if we
            # do, surface it so we know.
            if len(branches) >= 10_000:
                import sys
                print(f"  [warn] alignment branch count = {len(branches)}  "
                      f"max_branches={max_branches}  "
                      f"new_branches_in={len(new_branches)}",
                      file=sys.stderr, flush=True)
            if (stop_when_core_mapped and core_R and branches and
                    all(_core_complete(b.mapping) for b in branches)):
                if events is not None:
                    events.append({'type': 'done',
                                   'mapped': len(branches[0].mapping),
                                   'stop_reason': 'core_mapped',
                                   'core_size': len(core_R)})
                return branches
    if events is not None:
        events.append({'type': 'done',
                       'mapped': len(branches[0].mapping)})
    return branches


# -------------------- chirality scoring --------------------

def _chirality_violations(mapping, coords_R, coords_P,
                          broken, formed, elements_R, min_deg=4):
    """Count spectator-stereocenter chirality flips.
    Spectator = atom whose 4+ mapped neighbors are all preserved
    (no incident broken/formed bond). Sign = sign(det) of first-3
    neighbor displacement vectors against the 4th. Skip near-coplanar."""
    bad_atoms = set()
    for (i, j, _, _) in broken:
        bad_atoms.add(i); bad_atoms.add(j)
    inv = {v: k for k, v in mapping.items()}
    for (ip, jp, _, _) in formed:
        if ip in inv: bad_atoms.add(inv[ip])
        if jp in inv: bad_atoms.add(inv[jp])

    # Build neighbor lists from R-coords (assume bond-graph already filtered)
    # We use "any atom within reasonable bond distance" — use the bond-graph
    # caller passes us implicitly through coords ordering. For correctness
    # we re-derive from coords by looking up close neighbors.
    # Simpler: just take all atoms within 1.9 Å in R as "neighbors".
    n_R = len(elements_R)
    diff = coords_R[:, None, :] - coords_R[None, :, :]
    dist = np.linalg.norm(diff, axis=2)
    np.fill_diagonal(dist, np.inf)
    violations = 0
    checked = 0
    for u in range(n_R):
        if u in bad_atoms: continue
        if u not in mapping: continue
        nbrs = np.where(dist[u] < 1.9)[0].tolist()
        # all must be mapped + spectator
        if len(nbrs) < min_deg: continue
        if any(nb not in mapping for nb in nbrs): continue
        if any(nb in bad_atoms for nb in nbrs): continue
        # take first 4 neighbors
        nb4 = nbrs[:4]
        # signed volume in R-frame
        ru = coords_R[u]
        v1 = coords_R[nb4[1]] - coords_R[nb4[0]]
        v2 = coords_R[nb4[2]] - coords_R[nb4[0]]
        v3 = coords_R[nb4[3]] - coords_R[nb4[0]]
        det_R = float(np.linalg.det(np.stack([v1, v2, v3])))
        # corresponding atoms in P-frame
        pu = coords_P[mapping[u]]
        pn = [coords_P[mapping[nb]] for nb in nb4]
        v1p = pn[1] - pn[0]
        v2p = pn[2] - pn[0]
        v3p = pn[3] - pn[0]
        det_P = float(np.linalg.det(np.stack([v1p, v2p, v3p])))
        if abs(det_R) < 0.05 or abs(det_P) < 0.05:
            continue  # near-coplanar; sign unstable
        checked += 1
        if np.sign(det_R) != np.sign(det_P):
            violations += 1
    return violations


# -------------------- multi-seed driver --------------------

def _generate_seed_orders(g_R, n_trials, rng_seed=42):
    """Generate at most `n_trials` deterministic seed orderings.

    Heavy atoms are used as anchors first in graph order. Hydrogens are never
    used as explicit first seeds because they have few connectivity
    constraints. If more trials are requested than there are heavy atoms, pad
    with full random shuffles.
    """
    nodes = list(g_R.nodes())
    heavy = [n for n in nodes if g_R.nodes[n].get('element') != 'H']
    rng = random.Random(rng_seed)
    orders = []
    n_trials = max(0, int(n_trials))
    for h in heavy[:n_trials]:
        rest = [x for x in nodes if x != h]
        rng.shuffle(rest)
        orders.append([h] + rest)
    while len(orders) < n_trials:
        perm = list(nodes); rng.shuffle(perm); orders.append(perm)
    return orders


def align_from_arrays(elR, xyzR, wboR, elP, xyzP, wboP,
                      graph_floor=0.2, iso_tol=1.0,
                      dwbo_threshold=0.5,
                      n_seeds=10, max_branches=1_000_000,
                      chirality=True, return_all=False):
    """Pure-graph entry point: assumes (el, xyz, wbo) for R and P are
    already in hand (e.g. loaded from a pre-computed xtb cache). Runs the
    multi-seed PQ search + scoring. Returns the same dict as analyze_pq."""
    if Counter(elR) != Counter(elP):
        raise ValueError(f"composition mismatch: {Counter(elR)} vs {Counter(elP)}")

    g_R = build_graph(elR, wboR, bond_cut=graph_floor)
    g_P = build_graph(elP, wboP, bond_cut=graph_floor)
    p_orbits = _color_refine_orbits(g_P)

    orders = _generate_seed_orders(g_R, n_seeds)
    all_results = []
    for order in orders:
        branches = find_islands_pq(g_R, g_P, order,
                                   graph_floor=graph_floor, iso_tol=iso_tol,
                                   max_branches=max_branches)
        for b in branches:
            mapping = expand_mapping(b.mapping, g_R, g_P)
            mapping = symmetry_repair_mapping(
                mapping, wboR, wboP, g_R, g_P, p_orbits,
                dwbo_threshold=dwbo_threshold)
            broken, formed, _, _ = classify_bonds(
                mapping, wboR, wboP, dwbo_threshold=dwbo_threshold)
            chir = (_chirality_violations(mapping, xyzR, xyzP, broken, formed, elR)
                    if chirality else 0)
            score = (len(broken) + len(formed), chir, -len(mapping))
            all_results.append((score, mapping, broken, formed, chir))

    all_results.sort(key=lambda r: r[0])
    best = all_results[0]
    score, mapping, broken, formed, chir = best
    out = dict(
        elements_R=elR, coords_R=xyzR, wbo_R=wboR,
        elements_P=elP, coords_P=xyzP, wbo_P=wboP,
        mapping=mapping, broken=broken, formed=formed,
        n_mapped=len(mapping), n_broken=len(broken), n_formed=len(formed),
        chirality_violations=chir,
        score=score,
    )
    if return_all:
        out['all_scored'] = [(s, m, b, f, c) for (s, m, b, f, c) in all_results]
    return out


def analyze_pq(reactant_xyz, product_xyz, workdir,
               charge=0, uhf=0,
               graph_floor=0.2, iso_tol=1.0,
               dwbo_threshold=0.5,
               n_seeds=10, max_branches=1_000_000,
               chirality=True,
               return_all=False):
    """Run xtb on R and P, build graphs at graph_floor, run PQ search for
    n_seeds random orderings, score by (broken+formed, chir, -mapped)."""
    workdir = Path(workdir)
    elR, xyzR, wboR = run_xtb(reactant_xyz, workdir / "R", charge=charge, uhf=uhf)
    elP, xyzP, wboP = run_xtb(product_xyz, workdir / "P", charge=charge, uhf=uhf)
    return align_from_arrays(
        elR, xyzR, wboR, elP, xyzP, wboP,
        graph_floor=graph_floor, iso_tol=iso_tol,
        dwbo_threshold=dwbo_threshold,
        n_seeds=n_seeds, max_branches=max_branches,
        chirality=chirality, return_all=return_all)
