"""Resumable forward AAM campaign with bounded signed-event decoding.

Reruns AAM only. Compares with saved native-SLAP and SLAP-sweep witnesses,
rescored under the same raw-WBO policy. Limits never certify missing classes.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict
import gzip
import hashlib
import json
import os
from pathlib import Path
import subprocess
import threading
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / 'src'), str(ROOT / 'bench')]


def read(path):
    with gzip.open(path, 'rt') if path.suffix == '.gz' else path.open() as stream:
        return json.load(stream)


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(json.dumps(value, indent=2) + '\n')
    tmp.replace(path)


def input_path(args, case):
    return args.inputs / str(case) / 'input.json'


def config_record(args):
    previous = read(args.reference_repo / 'reports/holdout_cap1000_seed1_20260910/manifest.json')['original_config']
    return dict(previous, seed_count=args.seeds, branch_limit=args.cap)


def child(args):
    import random
    import numpy as np
    from rxn_core import AAMProblem, AAMSearchConfig, MolecularEndpoint, search_aam
    from rxn_core.artifacts import read_aam_checkpoint
    from rxn_core.event_patterns import SignedEventIndex, extract_path_events
    from validate_event_examples import compare_saved_slap
    case = args.case
    folder = args.run / f'case{case}'
    folder.mkdir(parents=True, exist_ok=True)
    raw = read(input_path(args, case))
    problem = AAMProblem(*(MolecularEndpoint(**raw[s]) for s in ('reactant', 'product')))
    expected_config = AAMSearchConfig(**config_record(args))
    cuts = folder / 'cuts'
    archive = cuts / 'aam.pkl.gz'
    if args.phase == 'search':
        random.seed(42)
        np.random.seed(42)
        start, cpu = time.perf_counter(), time.process_time()
        aam = search_aam(problem, expected_config, execution='reused_native', workers=1,
                         intermediate_dir=cuts, archive_format='checkpoint',
                         resume=(cuts / 'manifest.json').exists())
        save(folder / 'search.json', dict(case=case, config=asdict(aam.config), direction='R_to_P',
            cpu_seconds=time.process_time() - cpu, wall_seconds=time.perf_counter() - start,
            capped=aam.graph.capped, metrics=asdict(aam.metrics), archive_sha256=sha(archive)))
        return
    # Only read a trusted checkpoint generated by this campaign.
    recorded = read(folder / 'search.json')
    if recorded['archive_sha256'] != sha(archive):
        raise ValueError('Saved AAM archive hash differs from successful search record')
    aam = read_aam_checkpoint(archive)
    if aam.config != expected_config:
        raise ValueError('Saved search configuration differs from requested campaign')
    index = SignedEventIndex(problem)
    start, cpu = time.perf_counter(), time.process_time()
    deadline = start + args.decode_seconds
    slap = {}
    for method, filename, key in (
        ('native_slap', 'reports/holdout_cap1000_seed1_20260910/slap_scoring.json.gz', str(case)),
        ('slap_sweep', 'reports/holdout_slap_xyz_sweep_20260910/scored_candidates.json.gz', f'{case}/scored')):
        rows = read(args.reference_repo / filename)[key]['slap']
        best, patterns = None, {}
        for offset in range(0, len(rows), 64):
            batch = rows[offset:offset + 64]
            vectors = [[dict(row['mapping'])[a] for a in range(index.n)] for row in batch]
            counts = index.counts(vectors).sum(axis=1)
            for vector, count in zip(vectors, counts):
                total = int(count)
                if best is None or total < best:
                    best, patterns = total, {}
                if total == best:
                    p = index.describe(vector)
                    patterns.setdefault(p['id'], p)
        if best is None:
            raise ValueError(f'{method} has no saved complete witness for case {case}')
        slap[method] = dict(minimum=best, minimum_ids=sorted(patterns), patterns=patterns,
                            saved_witnesses=len(rows))
    window = max(v['minimum'] for v in slap.values()) + args.event_slack
    patterns, path_results = {}, []
    queries = representatives_scanned = 0
    complete = True
    reason = 'all_retained_full_paths_checked'
    # Keep the scan bounded in memory; duplicate event IDs are cheap to merge.
    batch = []
    def score_batch():
        nonlocal representatives_scanned
        if not batch:
            return
        vectors = [[dict(aam.graph.states[t].mapping)[a] for a in range(index.n)] for t in batch]
        for terminal, vector, total in zip(batch, vectors, index.counts(vectors).sum(axis=1)):
            if int(total) <= window:
                p = index.describe(vector)
                patterns.setdefault(p['id'], dict(p, terminal=terminal, provenance='saved_terminal'))
        representatives_scanned += len(batch)
        batch.clear()
    for terminal in aam.graph.terminals:
        if time.perf_counter() >= deadline:
            complete, reason = False, 'terminal_scan_budget'
            break
        if len(aam.graph.states[terminal].mapping) == index.n:
            batch.append(terminal)
            if len(batch) == 64:
                score_batch()
    score_batch()
    seed_ids = set(patterns)
    if complete:
        for path in aam.graph.paths():
            if len(path.mapping) != index.n:
                continue
            if time.perf_counter() >= deadline:
                complete, reason = False, 'case_decode_budget'
                break
            result = extract_path_events(path, aam.problem, index, max_events=window,
                seconds=min(2., max(0., deadline - time.perf_counter())), max_patterns=64)
            complete &= result['complete']
            if not result['complete']:
                reason = 'one_or_more_incomplete_families'
            queries += result['solver_queries']
            for p in result['patterns']:
                patterns.setdefault(p['id'], dict(p, terminal=path.terminal,
                    transitions=list(path.transitions), provenance='compressed_family'))
            path_results.append({k: v for k, v in result.items() if k != 'patterns'})
    save(folder / 'comparison.json', dict(case=case, name=raw.get('name', str(case)),
        config=asdict(aam.config), direction='R_to_P', event_policy=index.policy, max_events=window,
        search_capped=aam.graph.capped, saved_graph_window_complete=complete, reason=reason,
        full_terminals_scanned=representatives_scanned, path_count=len(path_results),
        path_results=path_results, solver_queries=queries, patterns=patterns,
        additional_classes_from_families=len(patterns.keys() - seed_ids),
        best_found=min((p['total'] for p in patterns.values()), default=None),
        slap=slap, comparisons=compare_saved_slap(slap, patterns, window, complete),
        cpu_seconds=time.process_time() - cpu, wall_seconds=time.perf_counter() - start,
        scope='Retained forward AAM graph and specified event window only. Saved SLAP witnesses '
              'are rescored; complete SLAP label families and chemical accuracy are not assessed.'))


class MemoryGuard:
    """Sample only this runner's child PIDs; terminate oversized work explicitly.

    RSS/available-memory checks are polling safeguards, not kernel hard limits.
    A killed case remains a resource-limited result, never a scientific miss.
    """
    def __init__(self, worker_mib, total_mib, reserve_mib):
        self.worker_kib = worker_mib * 1024
        self.total_kib = total_mib * 1024
        self.reserve_kib = reserve_mib * 1024
        self.lock = threading.Lock()
        self.active, self.stops, self.peaks = {}, {}, {}
        self.last_check = 0.
        self.peak_total_kib = 0

    def add(self, process):
        with self.lock:
            self.active[process.pid] = process

    def remove(self, pid):
        with self.lock:
            self.active.pop(pid, None)
            return self.stops.pop(pid, None), self.peaks.pop(pid, 0)

    def check(self):
        with self.lock:
            now = time.monotonic()
            if now - self.last_check < .5:
                return
            self.last_check = now
            live = {pid: p for pid, p in self.active.items() if p.poll() is None}
            if not live:
                return
            result = subprocess.run(['/bin/ps', '-o', 'pid=,rss=', '-p', ','.join(map(str, live))],
                                    text=True, capture_output=True, timeout=3)
            if result.returncode and result.stderr.strip():
                raise RuntimeError('Cannot inspect benchmark child memory: ' + result.stderr.strip())
            rss = {int(parts[0]): int(parts[1]) for line in result.stdout.splitlines()
                   if len(parts := line.split()) == 2 and int(parts[0]) in live}
            for pid, value in rss.items():
                self.peaks[pid] = max(self.peaks.get(pid, 0), value)
            total = sum(rss.values())
            self.peak_total_kib = max(self.peak_total_kib, total)
            available = None
            if sys.platform == 'darwin':
                vm = subprocess.run(['/usr/bin/vm_stat'], text=True, capture_output=True, timeout=3)
                if vm.returncode:
                    raise RuntimeError('Cannot inspect available-memory estimate')
                import re
                page_size = int(re.search(r'page size of (\d+) bytes', vm.stdout).group(1))
                fields = {key.strip(): int(value.strip().rstrip('.')) for line in vm.stdout.splitlines()[1:]
                          if ':' in line for key, value in [line.split(':', 1)]}
                # Matches the free + inactive estimate; compressed memory is not counted as free.
                available = sum(fields.get(key, 0) for key in ('Pages free', 'Pages inactive')) * page_size / 1024
            elif Path('/proc/meminfo').exists():
                available = next(float(line.split()[1]) for line in Path('/proc/meminfo').read_text().splitlines()
                                 if line.startswith('MemAvailable:'))
            victims = {pid: 'worker_memory_limit' for pid, value in rss.items() if value > self.worker_kib}
            remaining = total - sum(rss[pid] for pid in victims)
            for pid in sorted(rss, key=rss.get, reverse=True):
                if remaining <= self.total_kib:
                    break
                if pid not in victims:
                    victims[pid] = 'campaign_memory_limit'
                    remaining -= rss[pid]
            if available is not None and available < self.reserve_kib:
                victims.update({pid: 'system_memory_pressure' for pid in rss})
            for pid, reason in victims.items():
                if live[pid].poll() is None:
                    try:
                        live[pid].kill()
                        self.stops[pid] = reason
                    except ProcessLookupError:
                        pass


def bounded_process(command, env, log, timeout, guard):
    process = subprocess.Popen(command, env=env, stdout=log, stderr=subprocess.STDOUT)
    guard.add(process)
    deadline = time.monotonic() + timeout
    timed_out = False
    try:
        while process.poll() is None:
            guard.check()
            if time.monotonic() >= deadline:
                process.kill()
                timed_out = True
                break
            time.sleep(.1)
        process.wait()
    except BaseException:
        if process.poll() is None:
            process.kill()
        process.wait()
        guard.remove(process.pid)
        raise
    stopped, peak = guard.remove(process.pid)
    state = stopped or ('timeout' if timed_out else 'passed' if process.returncode == 0 else 'failed')
    return state, peak / 1024


def main(args):
    sources = {str(p.relative_to(ROOT)): sha(p) for base in (ROOT / 'src', ROOT / 'native')
               for p in base.rglob('*') if p.is_file() and p.suffix in ('.py', '.cpp', '.h', '.c')}
    sources['bench/run_event_campaign.py'] = sha(Path(__file__))
    sources['bench/validate_event_examples.py'] = sha(ROOT / 'bench/validate_event_examples.py')
    missing = [case for case in args.cases if not input_path(args, case).is_file()]
    if missing:
        raise SystemExit(f'Missing {len(missing)} inputs; no searches started. First missing cases: {missing[:12]}')
    references = ['reports/holdout_cap1000_seed1_20260910/slap_scoring.json.gz',
                  'reports/holdout_slap_xyz_sweep_20260910/scored_candidates.json.gz']
    identity = dict(cases=args.cases, config=config_record(args), direction='R_to_P', root_rng_seed=42,
        event_slack=args.event_slack, sources=sources,
        inputs={str(case): sha(input_path(args, case)) for case in args.cases},
        references={name: sha(args.reference_repo / name) for name in references})
    if args.resume:
        manifest = read(args.run / 'manifest.json')
        if manifest['identity'] != identity:
            raise SystemExit('Inputs, source, configuration, or selected cases changed; use a new run directory')
    else:
        args.run.mkdir(parents=True, exist_ok=False)
        save(args.run / 'manifest.json', dict(identity=identity, search_timeout=args.search_timeout,
            decode_seconds=args.decode_seconds, decode_watchdog=args.decode_seconds + 10,
            memory_limits_mib=dict(worker=args.worker_memory_mib, total=args.total_memory_mib, reserve=args.reserve_memory_mib),
            scope='All requested forward AAM cases; compare saved SLAP witnesses under raw-WBO events.'))
    if args.prepare_only:
        print('Prepared verified campaign manifest; no searches started.')
        return
    logical = os.cpu_count() or 1
    if logical < 2:
        raise SystemExit('Need at least two logical CPUs to leave one available')
    workers = min(args.workers, logical - 1)
    env = dict(os.environ, OPENBLAS_NUM_THREADS='1', OMP_NUM_THREADS='1', MKL_NUM_THREADS='1',
               VECLIB_MAXIMUM_THREADS='1', NUMEXPR_NUM_THREADS='1', PYTHONHASHSEED='0', PYTHONDONTWRITEBYTECODE='1')
    guard = MemoryGuard(args.worker_memory_mib, args.total_memory_mib, args.reserve_memory_mib)
    def run(case):
        folder = args.run / f'case{case}'
        folder.mkdir(parents=True, exist_ok=True)
        phases = []
        for phase, result_file, limit in [('search', 'search.json', args.search_timeout),
                                         ('decode', 'comparison.json', args.decode_seconds + 10)]:
            if (folder / result_file).exists():
                phases.append(dict(phase=phase, status='reused'))
                continue
            command = [sys.executable, str(Path(__file__).resolve()), '--phase', phase,
                '--case', str(case), '--inputs', str(args.inputs), '--reference-repo', str(args.reference_repo),
                '--run', str(args.run), '--seeds', str(args.seeds), '--cap', str(args.cap),
                '--decode-seconds', str(args.decode_seconds), '--event-slack', str(args.event_slack)]
            start = time.perf_counter()
            with (folder / f'{phase}.log').open('a') as log:
                state, peak = bounded_process(command, env, log, limit, guard)
            phases.append(dict(phase=phase, status=state, wall_seconds=time.perf_counter() - start,
                               peak_sampled_rss_mib=peak))
            save(folder / f'execution_{time.time_ns()}.json', phases)
            if state != 'passed':
                break
        record = dict(case=case, phases=phases)
        if (folder / 'comparison.json').exists():
            d = read(folder / 'comparison.json')
            record.update(complete=d['saved_graph_window_complete'], search_capped=d['search_capped'],
                          best_found=d['best_found'], comparisons=d['comparisons'], paths=d['path_count'])
        print(json.dumps(dict(case=case, phases=[p['status'] for p in phases], complete=record.get('complete'))), flush=True)
        return record
    started = time.perf_counter()
    with ThreadPoolExecutor(max_workers=workers) as pool:
        records = list(pool.map(run, args.cases))
    save(args.run / 'summary.json', dict(cases=records, elapsed_seconds=time.perf_counter() - started,
        workers=workers, logical_cpus=logical, numerical_threads_per_worker=1,
        peak_sampled_children_rss_mib=guard.peak_total_kib / 1024,
        complete_saved_graph_windows=sum(r.get('complete', False) for r in records)))
    if any(any(p['status'] not in ('passed', 'reused') for p in r['phases']) for r in records):
        raise SystemExit(1)


def parse():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--inputs', type=Path, required=True, help='Directory containing CASE/input.json')
    parser.add_argument('--reference-repo', type=Path, default=ROOT)
    parser.add_argument('--run', type=Path, required=True)
    parser.add_argument('--cases', nargs='+', type=int, default=list(range(140)))
    parser.add_argument('--seeds', type=int, default=1)
    parser.add_argument('--cap', type=int, default=2000)
    parser.add_argument('--workers', type=int, default=2)
    parser.add_argument('--search-timeout', type=float, default=60)
    parser.add_argument('--decode-seconds', type=float, default=20)
    parser.add_argument('--event-slack', type=int, default=1)
    parser.add_argument('--worker-memory-mib', type=int, default=1024)
    parser.add_argument('--total-memory-mib', type=int, default=4096)
    parser.add_argument('--reserve-memory-mib', type=int, default=6144)
    parser.add_argument('--resume', action='store_true')
    parser.add_argument('--prepare-only', action='store_true')
    parser.add_argument('--phase', choices=('search', 'decode'), help=argparse.SUPPRESS)
    parser.add_argument('--case', type=int, help=argparse.SUPPRESS)
    args = parser.parse_args()
    if min(args.seeds, args.cap, args.workers, args.worker_memory_mib, args.total_memory_mib) < 1 or args.reserve_memory_mib < 0 or args.search_timeout <= 0 or args.decode_seconds <= 0 or args.event_slack < 0:
        parser.error('positive counts/time budgets and nonnegative event slack required')
    if len(set(args.cases)) != len(args.cases) or any(i not in range(140) for i in args.cases):
        parser.error('case indices must be unique and in 0..139')
    if args.phase and args.case is None:
        parser.error('--case is required for a child phase')
    return args


if __name__ == '__main__':
    args = parse()
    (child if args.phase else main)(args)
