"""Post-hoc chemistry-relevant symmetry expansion helpers."""
from __future__ import annotations

from .primitives import _edge_wbo


def _v_equivalence_class(r, mapping, g_R, g_P, iso_tol=0.5):
    """For an already-mapped atom r with image v = mapping[r], find all
    OTHER P atoms v' that are locally equivalent to v under `mapping`:
      - same element
      - same WBO to mapping[u] for every u in r's R-fragment neighbors
      - same multiset of (element, WBO) for unmapped P-neighbors

    These are the atoms r could have mapped to interchangeably. Returns
    a list of v's including the original v as the first element."""
    v0 = mapping[r]
    n_el = g_R.nodes[r]['element']
    bonded_in_frag = [u for u in g_R.neighbors(r) if u in mapping]
    if not bonded_in_frag:
        return [v0]
    used_p = set(mapping.values())
    sig0 = None
    candidates = [v0]
    # Reference signature for v0
    def sig_of(v):
        unmapped = []
        for w in g_P.neighbors(v):
            if w in used_p or w == v: continue
            unmapped.append((g_P.nodes[w]['element'], round(g_P[v][w]['wbo'], 2)))
        return tuple(sorted(unmapped))
    sig0 = sig_of(v0)
    for v in g_P.nodes():
        if v == v0: continue
        if v in used_p: continue
        if g_P.nodes[v]['element'] != n_el: continue
        # WBO match to mapped fragment neighbors
        ok = True
        for u in bonded_in_frag:
            wR = _edge_wbo(g_R, u, r)
            wP = _edge_wbo(g_P, mapping[u], v)
            if abs(wR - wP) > iso_tol: ok = False; break
        if not ok: continue
        if sig_of(v) != sig0: continue
        candidates.append(v)
    return candidates


def expand_chemistry_relevant_atoms(mapping, broken_R_atoms, g_R, g_P, iso_tol=0.5):
    """Given a canonical bijection and the set of R-atoms that participate
    in broken/formed bonds, enumerate alternative bijections by swapping
    each chemistry-relevant atom's image with members of its equivalence
    class. Returns a list of (mapping, swap_path) tuples, where the
    canonical mapping is first.

    Each alternative is generated by a SWAP: r -> v', and the previous
    occupant of v' -> mapping[r]. We then re-validate WBO consistency on
    every R-edge among the mapped atoms.
    """
    alternatives = [(dict(mapping), [])]
    seen_keys = {tuple(sorted(mapping.items()))}
    for r in broken_R_atoms:
        if r not in mapping: continue
        eqv = _v_equivalence_class(r, mapping, g_R, g_P, iso_tol=iso_tol)
        if len(eqv) <= 1: continue
        v_orig = mapping[r]
        inv = {p: q for q, p in mapping.items()}
        for v_new in eqv[1:]:  # skip the original
            r2 = inv.get(v_new)
            new_m = dict(mapping)
            new_m[r] = v_new
            if r2 is not None:
                new_m[r2] = v_orig
            # Validate all R-edges still match
            valid = True
            for u in new_m:
                for w in g_R.neighbors(u):
                    if w not in new_m or u >= w: continue
                    wR = _edge_wbo(g_R, u, w)
                    pu, pw = new_m[u], new_m[w]
                    if abs(wR - _edge_wbo(g_P, pu, pw)) > iso_tol:
                        valid = False; break
                if not valid: break
            if not valid: continue
            key = tuple(sorted(new_m.items()))
            if key in seen_keys: continue
            seen_keys.add(key)
            alternatives.append((new_m, [(r, v_new)]))
    return alternatives
